### ISSUE TITLE
Auto format produces code looking bad in Android Studio code editor

### ISSUE THREAD

**Issue by giaur500** [dart-lang/dart_style#1021]
Please look what is the result:

![image](https://user-images.githubusercontent.com/26817206/115379513-e361b400-a1d1-11eb-9a89-5ef03e74ceb7.png)

It breaks Android Studio guide outlines actually. Any tips?

Expected ouptut:
![image](https://user-images.githubusercontent.com/26817206/115381946-671ca000-a1d4-11eb-9418-69075264b81a.png)

**Comment by munificent** [comment]
Can you include the full text of the code as text so that I can try to repro? Thanks.

**Comment by a14n** [comment]
It looks like you missed some trailing commas to have the expected tree output.

**Comment by giaur500** [comment]
Hi,
You can test with this sample code: https://pastebin.com/JUZW8Rcw

result:

![image](https://user-images.githubusercontent.com/26817206/115509757-1e6df100-a27f-11eb-83af-a3783e369cb9.png)

For example, line 42 and 43, are you sure is it ok?

**Comment by a14n** [comment]
https://flutter.dev/docs/development/tools/formatting#using-trailing-commas

After adding the following commas (and reformat) you should get what you expect:

```diff
57c57
<               )),
---
>               ),),
65c65
<             ]),
---
>             ],),
88c88
<     ));
---
>     ),);
```

**Comment by giaur500** [comment]
Ok, I was not aware of that. Alhough, trailing commas are redundant, so I am forced to add them to get formatter working correctly, there's no any other reason to use them.

Do you have any thoughts to make formatted working with any code with correct syntax, including redundant commas missing?

**Comment by munificent** [comment]
The formatter *is* formatting your code either with or without the trailing commas. But you get *different* formatting depending on whether the trailing comma is there or not. If you prefer the style it gives you with the trailing commas, you'll have to insert them in order to tell the formatter which style you prefer.

The reason it formats arguments lists with and without trailing commas differently is that the formatter is older than Flutter and support for trailing commas. The established formatting style before trailing commas were added to the language was:

```dart
function(
    argument,
    argument,
    argument,
    argument);
```

Where the `)` is after the last argument. That doesn't make any sense with a trailing comma:

```dart
function(
    argument,
    argument,
    argument,
    argument,); // <-- ???
```

The motivation for adding trailing commas is so that you can comment out an entire line to temporarily comment out an argument, which doesn't work if the `)` is on the same line.

I didn't want to radically change the style of all existing formatting code, so you only get that the different style where `)` is on its own line if you do actually have a trailing comma. I hope to eventually unify onto a single style, but that's a *lot* of work.

**Comment by giaur500** [comment]
Ok I understand. But to be honest, I don't understand how style generated without trailing commas could be even considered as useful. It rather looks like a bug, especially lines 42 and 43 from my code, that's not only about `)` on its own line or not.

**Comment by munificent** [comment]
Your code contains a mixture of argument lists with and without trailing commas, so you get a mixture of the two styles which is why it looks particularly bad. If you remove all of the trailing commas, you get:

```dart
  @override
  Widget build(BuildContext context) {
    return Flexible(
        child: Container(
            child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
          Padding(
              child: Row(children: <Widget>[
                Padding(
                    padding: EdgeInsets.only(right: 8.0),
                    child: Text(icon,
                        style: TextStyle(
                            color: Colors.lightBlue,
                            fontFamily: 'Fontawesome',
                            fontWeight: FontWeight.normal))),
                Flexible(
                    child: Row(children: [
                  Flexible(
                      child: Text(line1Text ?? "",
                          maxLines: 3,
                          style: TextStyle(
                              color: Colors.lightBlue,
                              fontWeight: FontWeight.normal)))
                ])),
                Visibility(
                    visible: counter != null,
                    child: Expanded(
                        flex: 0,
                        child: Text("#" + (counter ?? ""),
                            style: TextStyle(
                                color: Colors.black26,
                                fontWeight: FontWeight.normal))))
              ]),
              padding: EdgeInsets.only(
                  bottom: 3.0, left: 8.0, top: 10.0, right: 5.0)),
          Padding(
              child: Text(line2Text ?? "",
                  maxLines: 3,
                  overflow: TextOverflow.ellipsis,
                  style: line2Style),
              padding: EdgeInsets.only(
                  bottom: 3.0, left: 8.0, top: 10.0, right: 5.0)),
          Padding(
              child: Text(line3Text ?? "",
                  style: TextStyle(fontStyle: FontStyle.normal)),
              padding: EdgeInsets.only(
                  bottom: 10.0, left: 8.0, top: 10.0, right: 5.0)),
          Padding(
              child: Row(children: [
                Visibility(
                    child: Text(line4Text ?? "",
                        style: TextStyle(
                            fontStyle: FontStyle.normal,
                            color: line4Color != null
                                ? HexColor(line4Color)
                                : Colors.black)),
                    visible: line4Text != null),
                Spacer(),
                Padding(
                    padding: const EdgeInsets.only(right: 4),
                    child: Visibility(
                        visible: line5Text != null,
                        child: Text(line5Text ?? "",
                            style: TextStyle(
                                color: Colors.black26,
                                fontWeight: FontWeight.normal))))
              ]),
              padding: EdgeInsets.only(bottom: 10.0, left: 8.0, top: 0.0))
        ])));
  }
}
```

That's not super great because this style was designed before Flutter with it's huge deeply nested expressions existed. Before Flutter, most Dart expressions were relatively short or in imperative code. But the output here is at least reasonably consistent.

**Comment by vuciflutter** [comment]
> https://flutter.dev/docs/development/tools/formatting#using-trailing-commas
> 
> After adding the following commas (and reformat) you should get what you expect:
> 
> ```diff
> 57c57
> <               )),
> ---
> >               ),),
> 65c65
> <             ]),
> ---
> >             ],),
> 88c88
> <     ));
> ---
> >     ),);
> ```

Is it possible auto add comma to all file where need in lib folder?
