### ISSUE TITLE
could you support a format config that auto show imports

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/dart_style#1032]
such as `import 'package:foo/foo.dart';` for main.dart
but i just use the aaa method in main.dart,
i want auto change imports statement to:
`import 'package:foo/foo.dart' show aaa;` in main.dart when i dartfmt the code.

**Comment by munificent** [comment]
The formatter doesn't do any static analysis of your code, so it doesn't know which functions you're using or even which declarations a name refers to. This is important both for performance and so that it's possible to format code even while it's not in a totally valid state. (For example, you might be in the middle of a refactoring and want to reformat even though the code currently has type errors.) So this isn't something we could do in the formatter.
