### ISSUE TITLE
Option to Arrange code (order class members)

### ISSUE THREAD

**Issue by zs-dima** [dart-lang/dart_style#1052]
Could be nice to add option to auto arrange code according user defined styles and default Flutter/Dart guides.

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#order-other-class-members-in-a-way-that-makes-sense

https://www.jetbrains.com/help/idea/code-style-java.html#arrangement_tab

**Comment by munificent** [comment]
This is a reasonable request, but I think it is out of scope for the formatter, for a few reasons:

* Reordering code raises some subtle issues. In particular, there may be comments before or after members and it's not clear where those comments should end up. Dart format is designed to be run automatically on things like CI where a human does not vet the results, so it's important to minimize relying on heuristics or making formatting choices that have failure modes.

* It's not clear what ordering to prefer. Flutter has their suggested guideline *for code in the Flutter repo*, but there is no widely-used ordering guideline. "Effective Dart" deliberately does *not* suggest an ordering because it's not clear that any particularly mechanical ordering rule actually improves readability or maintainability.

* We already have implemented this in a number of other tools (the IntelliJ plug-in, I think VSCode, probably others), so it's not clear that it's worth the effort or reimplementing it in the formatter. (And, in particular, we would have to be careful to implement the exact same rules, or users will get frustrated when the tools fight with each other.)

Given those, and the opportunity cost of spending time on this versus other formatting improvements, I think this is pretty unlikely. However, I'll leave the issue open to gather feedback from users on desirability.

**Comment by zs-dima** [comment]
@munificent thanks for reply
Could I kindly ask you to mention any working IntelliJ plug-in for Dart or Flutter ?
It is plugins and built-in functionality for other languages as I mention above - but I saw nothing for Dart or Flutter.

**Comment by zs-dima** [comment]
@munificent at least could be nice to create IntelliJ plug-in or add Arrange code as IntelliJ Code Style options.

> It's not clear what ordering to prefer
it is clear with ordering options as IntelliJ has for Java and etc as I mentioned above

**Comment by munificent** [comment]
> @munificent at least could be nice to create IntelliJ plug-in or add Arrange code as IntelliJ Code Style options.
> 
> > It's not clear what ordering to prefer
> > it is clear with ordering options as IntelliJ has for Java and etc as I mentioned above

That does already exist in the Dart IntelliJ plug-in. Under the "Code" menu, it's "Sort Members in Dart File".

**Comment by zs-dima** [comment]
@munificent it is no "Sort Members in Dart File" under the "Code" menu as you could see
![image](https://user-images.githubusercontent.com/25195453/133250107-4282d7e0-5d26-4fd5-b8d1-f6b872365375.png)

**Comment by zs-dima** [comment]
@munificent Could I kindly ask yo u GitHub repository you suggest to post this issue to implement Arrange code functionality ?

**Comment by munificent** [comment]
> @munificent Could I kindly ask you GitHub repository you suggest to post this issue

I believe the Dart IntelliJ plugin is developed here: https://github.com/JetBrains/intellij-plugins/tree/master/Dart

**Comment by munificent** [comment]
I believe this is already handled well by our other tooling, at least in IntelliJ and Android Studio.
