### ISSUE TITLE
Extra space after comment inside generic

### ISSUE THREAD

**Issue by timsneath** [dart-lang/dart_style#1071]
I've commented out the type of `Pointer` for various reasons that aren't relevant to this issue, but I leave it in for the benefit of readers.

The extra space in the second example is a little odd, in that it makes it look like a less-than sign rather than the end of the generic.

```dart
  external Pointer/*<SAFEARRAY>*/ parray;
  external Pointer<Pointer/*<SAFEARRAY>*/ > pparray;
```

**Comment by munificent** [comment]
Yeah, I agree that isn't ideal. Should hopefully be an easy fix.

**Comment by HelioStrike** [comment]
Hey! Can I give this issue a shot? I haven't contributed to this repo before so I'm not sure what the rules of the land are.

**Comment by munificent** [comment]
I spent some time digging into this and, unfortunately, it's harder than it seems. Back before Dart 2.0, Dart had no support for generic methods. We started adding support for them in the "strong mode" type checker, but there was no syntax to actually write them. To work around that, users could write them using special comments and the parser used by strong mode would look for those.

To make those comments format less weird, the formatter would recognize them and not put spaces before and after them. The contents inside the comments in the issue Tim filed just *happens* to have the same structure used to recognize those magic generic method comments, but that's not always the case. The formatter also shouldn't put a space in code like:

```dart
List<int /* comment */> list;
```

But in this case, the `comment` doesn't look like a generic method comment, so your change won't recognize it.

Ideally, the formatter would never put a space between a comment in a generic parameter/argument list before the `>`. The problem is that at the point that it makes that decision, it doesn't know if the `>` is for generics or is actually an infix greater-than operator. We definitely *do* want spaces before `>` when used as an operator.

The right solution would be to plumb that context all the way through from SourceVisitor to ChunkBuilder. But that's a lot more work than your patch and probably not worth the effort given the rarity and harmlessness of the bug. The simplest thing to do is to just accept that, yes, you'll get a slightly funny looking space here.

Also, now that Dart 2.0 is far in the past, I can probably tear out the old code for treating generic method comments specially.

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) doesn't have any special support for the ancient pre-Dart 2.0 generic method comments, so you get:

```dart
  external Pointer /*<SAFEARRAY>*/ parray;
  external Pointer<Pointer /*<SAFEARRAY>*/> pparray;
```

That looks about right to me.
