### ISSUE TITLE
No extra line below constructor with super()

### ISSUE THREAD

**Issue by yelliver** [dart-lang/dart_style#1082]
Unformatted:
```
class A{
  A(this.name): super();
  final String name;
}

class B{
  B(this.name);
  final String name;
}
```

Formatted:
```
class A {
  A(this.name) : super();
  final String name;
}

class B {
  B(this.name);

  final String name;
}
```

We can see the difference between class A & B, I think there should be a extra line after A() constructor

**Comment by munificent** [comment]
Good catch. I agree there should be a blank line in both cases.

**Comment by harshit4762** [comment]
I can work on the issue, can you please make a pull request for this.

**Comment by munificent** [comment]
I don't know why the old formatter was inconsistent in this example, but the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) isn't. It outputs:

```dart
class A {
  A(this.name) : super();
  final String name;
}

class B {
  B(this.name);
  final String name;
}
```

It doesn't insert a mandatory blank line before the field, but I don't think it should either. The rule it has is that you get a mandatory after a member declaration that has a block (`{ ... }`) body. But, otherwise, it's up to the user as to whether there is a blank line there or not. So the new formatter is working as I expect.
