### ISSUE TITLE
Double indentation of Ternary Operator with multiline method calling

### ISSUE THREAD

**Issue by yelliver** [dart-lang/dart_style#1085]
We have this formatted code snippet:
```Dart
void main() {
  var result = condition
      ? doA(                                     //6-space indentation here
          param1,
          param2,
        )
      : doB();
}
```
it should be like this:
```Dart
void main() {
  var result = condition
    ? doA(                                       //should be 4-space indentation
        param1,       
        param2,
      )
    : doB();
}
```

**Comment by munificent** [comment]
This is formatted as expected. Expression indentation is generally +4 and in the formatted code you can see the `?` is indented four spaces relative to `var`, which is the statement that contains it.

**Comment by munificent** [comment]
I tested this example out using the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253). Here's what it produces:

```dart
void main() {
  var result =
      condition
          ? doA(
            param1, // comment to force split
            param2,
          )
          : doB();
}
```

Splitting between `=` and `condition` isn't ideal and is because of #1465. Aside from that, the rest of the indentation is what I expect. As I mentioned in the previous comment, expressions are generally indented +4 relative to the surrounding code, which is what the `?` and `:` lines relative to `condition`.
