### ISSUE TITLE
Please allow blank line before first member of a declaration (such as classes, mixins, functions etc)

### ISSUE THREAD

**Issue by weenzeel** [dart-lang/dart_style#1101]
I know this has been discussed before, but dismissed with arguments like, "most people seem fine with it".

Out of curiosity, what is the argument that makes reduced whitespace better than expanded whitespace. And why is the first declaration in a class different from the rest of the class etc, where blank lines between declarations are allowed? It's inconsistent.

Whitespace helps us organize different concepts more clearly. That'swhywestartedtoaddspacesbetweenwordsforinstance.

Making the blank line optional wouldn't break any code, right?

Thanks for the hard work on making sure that Dart is well formatted across the codebase.

**Comment by munificent** [comment]
> dismissed with arguments like, "most people seem fine with it".

That's not a "dismissal", that's an explanation. :)

The formatter works this way because its job is to automate as much whitespace as it can. Every bit of hand-authored whitespace that affects the resulting output is a place where a human may have to put mental effort into deciding how to handle it, and where other humans may argue with them about that choice. The formatter's job is to minimize that.

In this case, almost all users seem fine with eliminating and leading whitespace inside a body, so I think the formatter is doing users a service by not taking the original formatting into account.
