### ISSUE TITLE
`dart format` should default to current directory

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/dart_style#1109]
There's a bit of an asymmetry between `dart analyze`, which defaults to analyzing the current directory, and `dart format .` where we have to explicitly pass `.`. Is there a good reason for this, or can we default to formatting the current directory?

**Comment by munificent** [comment]
> Is there a good reason for this, or can we default to formatting the current directory?

Yeah, we discussed this when everything consolidated to the `dart` command. The key difference is that `dart analyze` doesn't modify any files on disk. It just reads and prints to stdout. That means it's safe to default to cwd since it can't do any harm.

With `dart format`, the most common way to run it is to overwrite files in place. The old dartfmt CLI required you to pass `-w` explicitly to get that behavior. (Without that, it just dumped the formatted output to stdout, which was rarely useful.) When I revamped the CLI options as part of bringing it into the `dart` command, I made overwriting the default behavior.

But that makes it riskier to then also default to running on cwd since it could then change files that you didn't intend.

Given that, we felt the safest CLI was to require you to specify what directory to run on, even though it's a little inconsistent with some other tools.
