### ISSUE TITLE
Consider allowing a `<` to make an over-long line even longer

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart_style#1114]
```dart
class C {
  final field = <
      String>[]; // Some really long comment that is going to break the line and even then it is too long
}
```

I think this is low priority since in most cases you'd solve it by shortening or moving the comment - the lines are too long anyway - but it did stand out to me when I noticed it a CL.

**Comment by munificent** [comment]
Yeah, I agree this formatting isn't great. It's a consequence of there being no solution that fits inside the page width. When it runs into those situations, the rule right now is to do whatever it takes to minimize the number of overflow characters, so it splits at `<` since that makes the subsequent line two characters shorter.

If it wasn't for the overflow, it would pick a nicer solution, as in:

```dart
class C {
  final field =
      <String>[]; // Some really long comment that is going to break the line.
}
```

It might be worth changing the heuristic and treating any amount of overflow as equally bad as another overflowing solution. Or maybe count the number of lines that overflow instead of characters.

Either way, this is relatively low priority, because the main goal when there isn't a solution that fits is to look funny enough to get users to change the code so that it can fit.

**Comment by munificent** [comment]
Closing this because I did change the formatter to no longer allow splitting on `<` at the beginning of a collection literal type annotation.
