### ISSUE TITLE
dart formatting incorrectly

### ISSUE THREAD

**Issue by 9tontruck** [dart-lang/dart_style#1126]
I installed dart/flutter extensions in my VSCode.

Here's my settings.json

```
{
    "explorer.confirmDelete": false,
    "dart.previewFlutterUiGuides": true,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false,
        "editor.defaultFormatter": "Dart-Code.dart-code",
    },
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.defaultFormatter": "Dart-Code.flutter"
}
```

But the auto-formatter keeps changing my DART code ugly like below:

  ```
@override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
          gradient: LinearGradient(
              colors: [Color(0xFF5AffBA), Color(0xFF94F9FF)],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight)),
      ...
```
The indents are 2 and 4 mixed and closing braces are not single-lined

What is wrong with my code and what should I do to fix it?

**Comment by munificent** [comment]
There's nothing wrong with your code, but there are two valid ways you might want your argument lists to look and the formatter doesn't know which one you want. Largely for historical reasons, it defaults to assuming you *do* want them indented +4 with the `)` on the same line as the last argument (because that was how almost everyone wanted their Dart code to look before Flutter existed).

To tell the formatter you don't want that and instead want it +2 with the `)` on the next line, add a trailing comma after the last argument before the `)`.
