### ISSUE TITLE
Incorrect formatting with function chaining.

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/dart_style#1135]
Formatted with dart format:
<img width="622" alt="Screenshot 2022-09-11 at 15 41 53" src="https://user-images.githubusercontent.com/35890159/189528106-92fbb95f-f794-4a22-a6cf-dcfcdf0a8c6a.png">

Seems, that correct formatting is:
<img width="651" alt="Screenshot 2022-09-11 at 15 42 21" src="https://user-images.githubusercontent.com/35890159/189528133-5014b0d0-b375-4d87-bad5-14cdcb482c18.png">

Dart SDK version: 2.17.6 (stable) on "macos_arm64"

**Comment by munificent** [comment]
This is working more or less as intended, but I agree the results don't look great. The formatter has heuristics around when to use "block-like" indentation for function expressions that appear as function arguments and when to use normal expression indentation. Those heuristics work pretty well in most cases, but not great in some like here.

In particular, the main reason why the indentation is inconsistent in your example is because the first function expression uses `=>` while the others use block bodies. You'll get more consistent formatting across the entire method chain if you use `() { ... }` for all three.

Would you mind including this code as text in the issue and not a screenshot? If I get a chance to tweak these heuristics, I would like to use this as a regression test but don't want to have to retype it all by hand.

**Comment by provBarryTolnas** [comment]
I captured above screenshot as text in case it is useful:
```dart
  file
      .readAsBytes()
      .then(
        (bytes) => ApiClient.instance.files.upload(
          ownershipType: ownershipType,
          file: MultipartFile.fromBytes(
            bytes,
            filename: filename,
          ),
        ),
      )
      .then(
    (storageFile) {
      _value = _value.add(id, FileUpload.fromStorageFile(storageFile));
      notifyListeners();
    },
  ).catchError(
    (Object e) {
      _value = _value.add(id, FileUpload.error(error: e, name: filename));
      notifyListeners();
    },
  );
```

**Comment by munificent** [comment]
> I captured above screenshot as text in case it is useful:

It is, thank you!

**Comment by munificent** [comment]
I ran the example through the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) and it produces:

```dart
  file
      .readAsBytes()
      .then(
        (bytes) => ApiClient.instance.files.upload(
          ownershipType: ownershipType,
          file: MultipartFile.fromBytes(bytes, filename: filename),
        ),
      )
      .then((storageFile) {
        _value = _value.add(id, FileUpload.fromStorageFile(storageFile));
        notifyListeners();
      })
      .catchError((Object e) {
        _value = _value.add(id, FileUpload.error(error: e, name: filename));
        notifyListeners();
      });
```

I believe that's exactly the requested output, so I think we're good.
