### ISSUE TITLE
dart format is slow

### ISSUE THREAD

**Issue by Waqar144** [dart-lang/dart_style#1149]
I am trying to write a "format on save" extension for kate which uses the command `dart format file.dart` to format the open file and then apply the changes, but it's so slow that the experience is not pleasant at all. 

The following 11 lines of code gets formatted in ~200 ms (!):
```dart
/**
 * Extra print function
 */
void printt(int a) {
  print('a is: $a');
}

void main(List<String> arguments) {
  print('Hello world!');
  printt(123);
}
```

```
~/projects/dart/hello (master)$ time dart format bin/hello.dart 
Formatted 1 file (0 changed) in 0.17 seconds.

real    0m0.543s
user    0m0.409s
sys     0m0.108s
```

Include in the time of `dart` starting up and shutting down and this is just too slow.

In comparison, `clang-format` formats [this 1300 lines file](https://invent.kde.org/utilities/kate/-/blob/master/apps/lib/kateviewspace.cpp)  in 50ms including process startup and shutdown.

---

Is there a missing flag or some option that can be used to make this faster?
 
---

**System**: AMD 4700U with 16G Ram and Samsung 980 SSD

**Comment by Waqar144** [comment]
Just to experiment, I wrote the following program to do formatting using `dart_style` package:
```dart
import 'package:dart_style/dart_style.dart';
import 'dart:io';

main(List<String> arguments) {
  final formatter = DartFormatter();
  try {
    final text = File(arguments[0]).readAsStringSync();
    print(formatter.format(text));
  } on FormatterException catch (ex) {
    print(ex);
  }
}
```
and it is able to format the same code in `0.015` seconds

**Comment by srawlins** [comment]
Yeah I think you're experiencing the overhead of the dart binary. I think LSP supports formatting through the Dart Analysis Server. @bwilkerson is that right?

**Comment by Waqar144** [comment]
Even if the `dart` binary overhead is excluded, the difference i.e.,

```
Formatted 1 file (0 changed) in 0.17 seconds.
```

vs

```
0.015 seconds
```

tells me that something extra is being done in the `format` side of things that slowing it down a lot more. Unless `dart format` uses some different library which is slower.

**Comment by munificent** [comment]
No, almost all of the time you're seeing is startup overhead. Here's the time it takes to format your original file on my machine:

```
time dart format --summary=profile temp.dart
Formatted temp.dart
0:00:00.190053: temp.dart
dart format --summary=profile temp.dart  0.36s user 0.07s system 115% cpu 0.372 total
```

If I duplicate the contents of the file a hundred times, it's:

```
Formatted /Users/rnystrom/Documents/temp.dart
0:00:00.181592: /Users/rnystrom/Documents/temp.dart
dart format --summary=profile ~/Documents/temp.dart  0.34s user 0.07s system 112% cpu 0.368 total
```

And a thousand times so (12,000 lines long):

```
Formatted /Users/rnystrom/Documents/temp.dart
0:00:00.467620: /Users/rnystrom/Documents/temp.dart
dart format --summary=profile ~/Documents/temp.dart  0.80s user 0.11s system 139% cpu 0.653 total
```

And just for kicks, 10,000 times (120k lines long):

```
Formatted /Users/rnystrom/Documents/temp.dart
0:00:01.174895: /Users/rnystrom/Documents/temp.dart
dart format --summary=profile ~/Documents/temp.dart  1.89s user 0.19s system 151% cpu 1.376 total
```

The formatter is pretty fast (except for some edge cases not hit by your example here), but Dart executables don't start up as quickly as native C/C++ ones because there's overhead from having a runtime, GC, object representation, etc.

If you're worried 200ms on a ten-line example means that it will take seconds to format a hundred-line file, it won't. If you're worried that 200ms is just too much overhead to invoke the formatter, then the best way to avoid that is to use the formatter as a library and call it using some long-running process.
