### ISSUE TITLE
Important performance regression since commit 7fd45d6 on a very big file

### ISSUE THREAD

**Issue by sroddy** [dart-lang/dart_style#1212]
I've discovered this issue when I tried to bump the version of dart_style from 2.2.5 to 2.3.0.

My build_runner command gets stuck (I've left it running for more than 10 minutes before killing it) when trying to format the output of a particularly big generated code file.
I've bisected the git log and figured out that the first commit in which the issue is present is after the merge of #1182 (commit 7fd45d6d1e2b93d873e08dcd54c8ba2a200c50f1). Before that commit, the step takes 2/5 seconds at most.
I've put a breakpoint and managed to dump the input string of the `DartFormatter.format` function inside the build step that causes it to hang.
I would prefer to avoid attaching that string here, as it contains some proprietary code, but I can send it via email if it can help you fix the issue.

Thanks

**Comment by sroddy** [comment]
I've managed to reproduce the regression on the attached snippet of code, this is the output (elapsed time) on my machine before and after:
- 87ms     with commit 35a5d9fc05681b0f383a15aa661329bbaa0209dc
- 1857ms with commit 7fd45d6d1e2b93d873e08dcd54c8ba2a200c50f1

[regression.dart.zip](https://github.com/dart-lang/dart_style/files/11359535/regression.dart.zip)

**Comment by munificent** [comment]
Thanks, I'll take a look.

**Comment by munificent** [comment]
OK, I know what's going on. The change to allow inline case bodies (c9e51918c47388ef53303bbdc3b30bc9e840a51b) incidentally fixed a long-standing bug where metadata splitting behavior across parameters wasn't correct. It was always the intent that if a metadata annotation on a parameter splits, then all metadata annotations across all parameters in the parameter list should split.

Unfortunately, because of the bug, the line splitter didn't enforce that rule. The above commit fixes the behavior. But in order to fix that, all parameters in a parameter list must go through the line splitting algorithm process instead of line splitting each parameter independently. Line splitting is the slowest part of formatting and can get very slow if you throw more code at it at once.

Your program happens to contain a particularly long parameter list (85 parameters), so line splitting takes too long and it gives up.

I'll spend some time and see if I can come up with a better way to handle this.
