### ISSUE TITLE
Option to keep manual breaks.

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/dart_style#1222]
Thinking in sometimes using editors side-by-side, such as this:

![image](https://github.com/dart-lang/dart_style/assets/379339/8193dcff-95dd-41a5-a6f2-77cd8adf62c2)

I set my VSCode `editor.rulers` and `dart.lineLength` at `89` (since this is the max column before horizontal score).

Problem is, with this settings, some lines just don't seem to be right:

![image](https://github.com/dart-lang/dart_style/assets/379339/861d34cf-2409-4654-ad6e-bc3ce4381173)

It would be nice if the formatter could break those lines on the dots:

```dart
var user = await _isar
  .users
  .filter()
  .userIdEqualTo(authenticatedUser.id)
  .findFirst();
```

(in the first screenshot, at left panel, it already done that on line 91, but on the right panel, it failed to do the same at line 33)

**Or some option that allowed manual breaks immutable (meaning: if I wrote that line in that way, dart formatter would recognize and maintain the line breaks on `.`)**

**Comment by munificent** [comment]
The formatting you see here is working as intended, but it might not be what all users would prefer. It moves the entire expression to the next line because doing so allows it to keep the whole method chain together. You get two lines instead of five.

As far as why you can't opt out, the FAQ discusses this some: https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code
