### ISSUE TITLE
Allow explicit new lines in call chains

### ISSUE THREAD

**Issue by andrei-bucurei** [dart-lang/dart_style#1244]
The formatter decides to keep long call chains on one line if it does not exceed (too much) the max line length.
For example I have this code:
```
return db.appointments.where().userAccountIdEqualTo(userAccountId).watch(fireImmediately: true);
```
I naturally write this code formatted like this only to have the formatter break it later:
```
return db.appointments
        .where()
        .userAccountIdEqualTo(userAccountId)
        .watch(fireImmediately: true);
```
In some cases this is more readable and it's clearly not against `dart_style` as this would be the same style used if the line was longer.
I believe the formatter should give us more freedom as long as we stay in the `dart_style`.

**Comment by eernstg** [comment]
The formatter intentionally does not provide many ways to customize the layout, but you do have some ways to adapt its behavior: In particular, if you put a `//` comment at the end of a line then the line break at that points will be preserved, and this determines the layout of the rest of the expression:

```dart
// Preserve the multi-line layout of the return expression using `//`:
return db.appointments //
        .where()
        .userAccountIdEqualTo(userAccountId)
        .watch(fireImmediately: true);
```

**Comment by munificent** [comment]
This is working as intended (though I agree that in some fairly rare cases, it would look better to split even when the unsplit method chain does fit in the page width).

The reasoning for this behavior is mainly around [reversibility](https://github.com/dart-lang/dart_style/wiki/Reversibility-principle). Imagine if you:

1. Rename some method in a method chain so that it ends up not fitting in one line.
2. Run the formatter. The formatter splits it onto multiple lines.
3. Decide you like the old name better and undo the name change.
4. Run the formatter.

On step four, you *should* get back to your original code. But if the formatter treated a newline in a method chain to mean "always split", it wouldn't give you that. The problem is that the formatter has no way to distinguish "newline a human deliberately added" from "newline the formatter itself added in a previous invocation but the human doesn't care about".

The general solution is that, for the most part, it ignores the incoming whitespace entirely. This means you have less control over the output, but also means that formatting is more robust in the presence of refactoring and undo.

Also... it's just one less thing for you to worry about. Let the formatter decide whether your method chains should split or not.
