### ISSUE TITLE
Respect 80 character limit

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/dart_style#128]
Even if a line break is possible, the formatter seems to not respect the 80 character limit:

$ cat x.dart
var foo = {
  'foobar': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
};

$ dart_style -w x.dart
Formatted x.dart

$ lc.py x.dart 
file 'x.dart:2' has 81 characters

**Comment by seaneagan** [comment]
According to e.g. #74 the formatter only touches whitespace, so guessing the same applies here.  But even if the formatter cannot guarantee the 80 character limit, it would be nice if it can give some indication that it could not, such as via its exit code.

**Comment by munificent** [comment]
Like Sean says, the formatter does the best it can and aims for the page width, but can only do so much. After all, it's possible to have a single identifier whose name is longer than 80 characters.

In you case, Martin, it does find a solution:

```dart
// 456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
var foo = {
  'foobar':
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
};
```

You may have an older version since splitting after map keys is relatively new. I'm publishing versions of the formatter now, so you can just do:

```
$ pub global activate dart_style
```

to install the latest published version. I don't think it's that useful to tell users if it couldn't fit everything inside 80 columns since it doesn't promise to to begin with.
