### ISSUE TITLE
Preserve extra leading whitespace for multiline strings.

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#134]
It's useful to use leading whitespace to indicate which lines of multiline strings are continuations of previous lines, and which will be separate lines in the output. For example, currently:

``` dart
"A shelf request's underlying data stream was hijacked.\n"
"This exception is used for control flow and should only be handled by a "
  "Shelf adapter.";
```

is formatted as

``` dart
"A shelf request's underlying data stream was hijacked.\n"
"This exception is used for control flow and should only be handled by a "
"Shelf adapter.";
```

This seems like a good place to consider the original whitespace to be a hint. Alternately, automatically add indentation for lines that come after `\n"`.

**Comment by munificent** [comment]
It's been almost a decade, so I'm going to call this not-gonna-happen. :)

The formatter tries to format multi-line strings in such a way that the lines all line up when possible, like:

```dart
var x =
    'line'
    'another'
    'last';
```

And it also has some smarts now to indent subsequent lines if *not* doing so would likely be confusing. If you have a argument list or collection literal with multiple string arguments, it indents subsequent lines in multiline strings so that it's clearer where each argument/element begins:

```dart
[
  'line'
    'another',
  'next element',
];
```

That seems to work pretty well (it's been around for years). And I suspect that this feature would interact with that one poorly, so I'd rather just not do this one.
