### ISSUE TITLE
Mark files to skip

### ISSUE THREAD

**Issue by Fox32** [dart-lang/dart_style#147]
I like that I can run the formatter for the whole directory. But in my project there are some files, were the formatter will never be able to do a good job. These are files that have a specific formatting that make the file better readable/understandable. My files are quite similar to the [ones in the ```lib/src/content``` folder of hauberk](https://github.com/munificent/hauberk/tree/master/lib/src/content). Good examples are ```monsters.dart``` and ```recibes.dart```. For now I have to revert the files after running the formatter.

It would be usefull to skip specific files while formatting. 

I'm not sure what a good way of marking them is. Some things that came into my mind: @metadata, specific comment, or something like .gitignore (could also be integrated into another config file, e.g. one that specifies the line length for the project).

**Comment by munificent** [comment]
I think this is a bit more complex than I want to do in the formatter. It's pretty easy to just invoke the formatter with an explicit list of files that doesn't contain the ones you don't want it to touch. And, philosophically, I'm disinclined to make it easy for people to *not* format their code.

(Also, for what it's worth, the formatter would do a decent job of the stuff in hauberk. :smile:.)

**Comment by zoechi** [comment]
I can imagine that devs sometimes have a different opinion than the formatter. If it is difficult/cumbersome to make the formatter do what the dev wants, this could lead to abandoning the formatter entirely for a project.
As mentioned, I'm really satisfied with the results so far, but I can imagine situations where I want to ensure that my manual formatting is preserved.
I would prefer a way which is aligned with how the linter does it (where this is issue is still open) where scopes can be marked for exclusion of specific lint rules (I guess annotations offer themselves)

**Comment by munificent** [comment]
> I can imagine that devs sometimes have a different opinion than the formatter.

The problem is what when devs disagree with the formatter, they tend to be disagreeing with *each other* as well. The latter is the key problem that the formatter exists to solve.

The formatter can't please everyone all the time, but even when it doesn't, it is at least *consistent* in its output. Consistency has its own value independent what the actual formatting is, and I don't want to sacrifice that.

> I would prefer a way which is aligned with how the linter does it (where this is issue is still open) where scopes can be marked for exclusion of specific lint rules (I guess annotations offer themselves)

This is a big part of why the linter is a separate project. With the latter, the rules become more semantic, more open-ended, and more open to interpretation. That makes it much harder to globally enforce a single set of lint rules onto the whole world.

All the formatter does is touch your whitespace. That's such a narrow scope that I think it's reasonable to have a single configuration for the whole world. Of course, you don't *have* to run the formatter on your code. But when you do, I want it to produce the exact same output for everyone who uses it. The whole point of having a formatter is to increase consistency, and configurability—or even just easy opting out—doesn't get us closer to that.
