### ISSUE TITLE
Tall style: Multiline array literals in a parameter list should induce a trailing commas

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/dart_style#1528]
Apologies for the spam. I hope this isn't inappropriate!  
I came across an issue related to multiline array literals inside ConstructorInvocations.

The following:

```dart
          result = ProviderScope(
            overrides: [
              selectedCharacterId.overrideWithValue(split.last),
            ],
            child: const CharacterView(),
          );
```

Now becomes:

```dart
          result = ProviderScope(overrides: [
            selectedCharacterId.overrideWithValue(split.last),
          ], child: const CharacterView());
```

That feels incorrect. I assume this is a bug?

**Comment by munificent** [comment]
> Apologies for the spam. I hope this isn't inappropriate!

Separate issues are super helpful!

This output is deliberate but perhaps not ideal. We definitely don't *always* want to induce trailing commas if an argument list contains a collection literal. Both the old formatter and the entire hand-formatted Flutter repo heavily feature code like:

```dart
doStuffWith([
  some,
  things,
]);
```

It would be *really* annoying if that became:

```dart
doStuffWith(
  [
    some,
    things,
  ],
);
```

And given Flutter's predilection for named parameters, I think it's also important to support:

```dart
doStuffWith(children: [
  some,
  things,
]);
```

At the same time, sometimes a collection literal should still force an argument list to split. Otherwise things can get too cramped like:

```dart
doStuffWith(someArgument, [
  some,
  stuff,
], anotherArgument, [
  wait,
  even,
  more,
  stuff,
], aFinalOne);
```

So then the question is under what conditions does a collection literal (or function expression, or other block-formattable thing) *not* force the surrounding argument list to split?

Those heuristics are quite subtle and weird in the old formatter. The new formatter has simpler rules, but they still may need some tweaking. In fact, there's still a TODO in the new formatter about it:

```dart
// TODO(tall): These heuristics will probably need some iteration.
```

In this specific example, I think one reasonable tweak is to say that if there are multiple named arguments, then that means no special block formatting.

**Comment by rrousselGit** [comment]
IMO the heuristic is simple:

Is the multiline expression the last argument in an Argument List?
We can ignore the trailing comma.

If not, trailing comma needed.

```dart
// ok:
fn([a], [
  b
  c,
]);

// ko:
fn([
  b, 
  c,
], [a])
```

This would apply to anything that spans over multiple lines.

Including mutline strings and closures.

**Comment by rrousselGit** [comment]
> At the same time, sometimes a collection literal should still force an argument list to split. Otherwise things can get too cramped like:
> 
> ```dart
> doStuffWith(someArgument, [
>   some,
>   stuff,
> ], anotherArgument, [
>   wait,
>   even,
>   more,
>   stuff,
> ], aFinalOne);
> ```

For me I'd accept:
```dart
doStuff(
  someArg,
  [some, stuff],
  [even, more, stuff],
  aFinalOne,
);
```

And optional add a comma in the individual lists if they are too long:

```dart
doStuff(
  someArg,
  [some, stuff],
  [
    even,
    more,
    stuff,
  ],
  aFinalOne,
);
```

The extra indentation helps visualizing where an argument starts/ends. That warrants a line consisting nothing but [ to me.
