### ISSUE TITLE
dartformat replaces comma in constructor parameter list with open paren

### ISSUE THREAD

**Issue by cbracken** [dart-lang/dart_style#156]
After invoking dartformat on the following code:
```dart
class Foo {
  final bar;
  final baz;
  Foo(int this.bar(), this.baz);
}

main() {
  var f = new Foo(() => 4, 2);
  print(f.bar());
  print(f.baz);
}
```

The line
```dart
Foo(int this.bar(), this.baz);
```
is rewritten to:
```dart
Foo(int this.bar()( this.baz);
```

**Comment by munificent** [comment]
What a tricky corner case! This only manifests with initializing formals that have a declared function type and are not the last one in the parameter list. It's caused by [#22245](https://code.google.com/p/dart/issues/detail?id=22245) in the analyzer. I'll try to work around it in the formatter until that gets fixed.
