### ISSUE TITLE
Line longer than 80 characters in class type parameters

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/dart_style#1568]
https://dart-review.googlesource.com/c/sdk/+/386736 introduces several declarations that look similar to this:

```dart
abstract interface class TypeAnalyzerOperations<
        TypeStructure extends SharedTypeStructure<TypeStructure>,
        Variable extends Object,
        TypeParameterStructure extends SharedTypeParameterStructure<TypeStructure>,
        TypeDeclarationType extends Object,
        TypeDeclaration extends Object>
    implements FlowAnalysisOperations<Variable, SharedTypeView<TypeStructure>> {
  ...
}
```

Note that the line `TypeParameterStructure extends SharedTypeParameterStructure<TypeStructure>,` is longer than 80 characters. The formatter insists on placing this text all on the same line, causing failures in the `lines_longer_than_80_chars` lint.

To see more examples, search for the text `// ignore: lines_longer_than_80_chars` in https://dart-review.googlesource.com/c/sdk/+/386736.

**Comment by srawlins** [comment]
That's the kind of bug that I'd be tempted to just turn a blind eye to. 😅 

Half joking. This bug is the kind of thing that indicates, maybe the code isn't readable longer than 80 chars, and maybe it isn't readable wrapped into multiple lines; maybe there is a naming solution, or a typedef solution, that results in more readable code.
