### ISSUE TITLE
cascade linebreaks are too aggressive

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#172]
```diff
-      out..write('.')..write(node.methodName.name);
+      out
+        ..write('.')
+        ..write(node.methodName.name);
```

Here's the chain of thought:
* `left + "." + right` is pretty normal in languages without interpolation.
* With a StringBuilder/Buffer it becomes `sb.add(left).add('.').add(right)`.
* In Dart we decided `return this` all over in types like StringBuffer was excessive, so instead introduced cascades. So it becomes `sb..add(left)..add('.')..add(right)`
* but now formatter treats it differently. This would encourage me to use methods and make my "pretty printer" type `return this` everywhere.

Not sure if that's the intent but it seems like the different features aren't adding up quite right.
(original context https://github.com/dart-lang/dart_style/issues/155#issuecomment-72536376)

Here's another example I just ran into:

```diff
-        for (var e in _edits) sb..write('\n    ')..write(e);
+        for (var e in _edits) sb
+          ..write('\n    ')
+          ..write(e);
```

the message I'm getting from this is "don't use cascades" ... which, eh, is okay, but it's occasionally a nice syntax for infix append style operations. Imagine C++ where every cout `<<` was on a new line:

```diff
-cout << "This " << " is a " << "single C++ statement";
+cout << "This "
+    << " is a "
+    << "single C++ statement";
```
(example from http://www.cplusplus.com/doc/tutorial/basic_io/)

**Comment by jacob314** [comment]
multiple repetitive statements on a line require less cognitive load and should follow the same rules as deciding whether an array should be on a line rather than the general rules for cascades.
e.g. consider
foo..bar(asdfasdfasdf)..baz(adsfkjasdf)..fobar(asdfkjasd fjaksdfljasdf)
foo..write(asdfasdfasdf)..write(adsfkjasdf)..write(asdfkjasd fjaksdfljasdf)
foo.write([asdfasdfasdf, adsfkjasdf, asdfkjasd fjaksdfljasdf])
I'd argue the last two should be formatted on one line while the first should be split into multiple lines.

**Comment by jmesserly** [comment]
ah, good point. Yeah that rule would work for me :+1:

**Comment by munificent** [comment]
So you're saying we should allow multiple cascades on one line only if they all use the same method name? So this is OK:

```dart
items..add("one")..add("two")..add("three");
```

But as soon as you do:

```dart
items..add("one")..add("two")..add("three")..sort();
```

it becomes:

```dart
items
  ..add("one")
  ..add("two")
  ..add("three")
  ..sort();
```

I can't imagine this making users happy, but maybe. Honestly, I feel like we're just trying really hard to make cascades happen and we should just admit that they're not that usable.

For example, I assume we would not allow multiple cascades on a single-line if they are setters:

```dart
foo..bar = "1"..bar = "2";
```

So the rules for formatting cascades are:

1. If it's a series of cascades.
2. And all the methods have the same name.
3. And they aren't setters.
4. Then allow them to be on one line.
5. If they fit.
6. If not, put each on its own line.
7. With indentation rules different from all other continued expressions.

The amount of special case logic in the formatter for cascades is just insane and, as this bug shows, still causes lots of problems. For example, the special-case "only indent cascades 2" collides with how collections and functions are indented:

```dart
object
  ..first()
  ..second(() {
  ugh.should.not.line.up.with.cascades();
})
  ..third();
```

So we probably need to do more special stuff for cascades for this too. :(

**Comment by jmesserly** [comment]
> only indent cascades 2

only make them +4?

**Comment by munificent** [comment]
> only make them +4?

That's what I did at first and @jacob314 filibustered me into special-casing them to +2.

**Comment by jacob314** [comment]
Fixed this with https://codereview.appspot.com/212600043
foo..write(...)..write(...)
will now stay as one line but
foo..write(...)..somethingElse(...)
will not
not all cases are handled ideally
foo..write(...)..write(....)..finalize()
gets formatted as 
foo
  ..write(...)
  ..write(....)
  ..finalize()
instead of the perhaps cleaner 
foo
  ..write(...)..write(....)
  ..finalize()

Feel free to reopen or file a new bug for just the cases fix fix doesn't handle.
