### ISSUE TITLE
dartfmt without any arguments just hangs

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#179]
`Without an explicit path, dartfmt processes the standard input.` I guess this means that dartfmt waits for stdin when called without any arguments.
It's still a bit weird. 
Usually command line commands print usage information when no arguments are passed or do some default behavior (like ls), at least they usually do something visible.
I think it would be a good idea to add an explicit parameter to switch to stdin mode.

**Comment by munificent** [comment]
Yeah, I agree this is confusing. I'd prefer something like an explicit `-` arg to mean "read from stdin". I did it this way to be compatible with the old formatter's behavior.

Hey, @pq, do you think it will break anything if I make this change?

**Comment by pq** [comment]
I'm fine with an explicit `-`.  (For the record, I was cribbing [gofmt](https://golang.org/cmd/gofmt/) with the no args thing but that's neither here nor there.)  Anyway, if you go this route before DartEditor is entirely backed by the analysis server, you'll need to update it appropriately.  I can do that so that's not big deal.  We just need to coordinate.

Otherwise, I understand that sublime is playing with the analysis server for errors and warnings... Any idea if they're getting formatting from the server too?

**Comment by cbracken** [comment]
I'm actually a fan of the current behaviour; it's exactly what I'd expect. Reading from stdin when no args are specified is pretty standard (unix) behaviour. `cat`, `dc`, `sed`, `sort`, `uniq` all feature this same behaviour.  That said, [dartbug.com/21796](http://dartbug.com/21796) is an annoyance.

If this is changed, you'd want to make sure that piped input like `dartfmt < somefile.dart` still works. I'd be very surprised if there wasn't tooling relying on that.

**Comment by pq** [comment]
Right.  That was the rationale as I recall (`gofmt` just being an instance).  In light of @cbracken's comments I'd probably leave it well enough alone but then, yeah, there's [dartbug.com/21796](http://dartbug.com/21796)...

**Comment by munificent** [comment]
Alright, @cbracken, I'm convinced.

**Comment by guillermooo** [comment]
> Otherwise, I understand that sublime is playing with the analysis server for errors and warnings... Any idea if they're getting formatting from the server too?

ST calls the old `dartfmt`, btw.
