### ISSUE TITLE
Rename package/repo to `formatter`

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_style#180]
This package/repo essentially provides a "formatter for dart".  `dart_style` doesn't really convey that, and `formatter` would be more consistent with the `linter` package.

**Comment by munificent** [comment]
I think the package name *should* have "dart" in it, since it's specific to styling Dart code. (This is different from the guideline to avoid putting "dart" in a package name because the package is *implemented* in Dart. In this case, "dart" means "this package is for working with Dart code".)

I could change the name to `dart_formatter` or `dartfmt`, but I'm not sure if it's worth the effort. The former is more precise, but it's still different from the command name so doesn't really clarify much. The latter matches the command name, but is now an ugly name.

I still wouldn't be surprised if we ended up with more functionality than just the formatter in here, so I don't know if it adds value to tighten the name today.

**Comment by seaneagan** [comment]
Came up here:

https://github.com/google/grinder.dart/issues/168#issuecomment-93800531
