### ISSUE TITLE
Arguments alignment is incorrect

### ISSUE THREAD

**Issue by scheglov** [dart-lang/dart_style#193]
Consider the following change after formatting.

```
-    _assertLinkedGroup(
-        change.linkedEditGroups[index++],
-        ['int i'],
-        expectedSuggestions(
-            LinkedEditSuggestionKind.TYPE,
-            ['int', 'num', 'Object', 'Comparable']));
+    _assertLinkedGroup(change.linkedEditGroups[index++], [
+      'int i'
+    ], expectedSuggestions(
+        LinkedEditSuggestionKind.TYPE, ['int', 'num', 'Object', 'Comparable']));
```

  I think it actually makes the code harder to read.

1. Why does it split ['int i'] instead of splitting on the highest level - arguments of _assertLinkedGroup?

2. Why does its closing "]" have the same indentation as the statement?

**Comment by munificent** [comment]
> 1\. Why does it split ['int i'] instead of splitting on the highest level - arguments of _assertLinkedGroup?

The proximate answer is that It treats collection literals as pretty low cost when choosing which splits are best. The reason it does that is because it tends to produce pretty nice results most of the time. For example, given:

```dart
someMethod(argument, argument, argument, [argument, argument, argument, argument]);
```

I think this:

```dart
someMethod(argument, argument, argument, [
  argument,
  argument,
  argument,
  argument
]);
```

is better than:

```dart
someMethod(
    argument,
    argument,
    argument,
    [argument, argument, argument, argument]);
```

Of course, reason people may disagree. Some of this comes down to aesthetic preference. Also, formatting interacts with API design in interesting ways. I deliberately design my APIs to tend to have function or collection literal arguments as the last argument because I find those format better.

> 2\. Why does its closing "]" have the same indentation as the statement?

This is according to the rules of the style guide. It's always been this way (and, I believe follows the Google JS style). This is the part of the style guide that bothers the most people.

I'm not opposed to changing it, but we'd need to implement the change in the formatter and run it on a large corpus to ensure a different rule really does improve most code. Right now, I'm not convinced that's the case. The indentation rules can produce strange output in some cases, but work really well in lots of others.
