### ISSUE TITLE
Strange and inconsistent indent in method chain

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/dart_style#198]
With certain forms of method chaining using anonymous nested functions the indentation of the chained calls is strange and inconsistent. I'm unsure if this is the same as [issue 145](https://github.com/dart-lang/dart_style/issues/145).

Using dartfmt 0.1.6

Example - notice that the last chain element is treated differently:
```
  testThat('backward navigation is disabled when at end of stream',
      when: (TaskList taskList, TaskService taskService) {
    var cursorPageNo = 0;
    final streamCtrl = initCustomTaskServiceMock(taskService,
        canMoveTo: (pageNo) => pageNo < 0 ? false : true,
        getCurrentPageNumber: () => cursorPageNo);

    first('attach tasklist', () {
      taskList.attach();
      addTasks(streamCtrl);
    })
        .thenExpect('pager at page 1', () => {
      taskList.currentPageNo: 1,
      taskList.backwardPaginationDisabled: isFalse
    })
        .then('go to page 2', () {
      taskList.nextPage();
      addTasks(streamCtrl, count: 1);
      cursorPageNo = 1;
    }).thenExpect('pager unchanged', () => {
      taskList.currentPageNo: 2,
      taskList.backwardPaginationDisabled: isTrue
    });
  });
```

**Comment by munificent** [comment]
The output is a little strange here, but that's in part because the code itself is less regular than it looks. With `first()` and `.then()` you are passing a block-bodied function (`() { ... }`). With `.thenExpect()` you are passing a lambda-bodied function whose body is a map literal (`() => { ... }`).

Lambda-bodied functions and block-bodied functions have different formatting rules. In particular, they cause a surrounding method chain to split differently. The lambda functions are treated like regular arguments where block functions cause the method calls before and after to become their own independent method chains. If you use block bodies for all of the functions, you're closer to the kind of code the formatter has in mind, and you'll get better output:

```dart
testThat('backward navigation is disabled when at end of stream',
    when: (TaskList taskList, TaskService taskService) {
  var cursorPageNo = 0;
  final streamCtrl = initCustomTaskServiceMock(taskService,
      canMoveTo: (pageNo) => pageNo < 0 ? false : true,
      getCurrentPageNumber: () => cursorPageNo);

  first('attach tasklist', () {
    taskList.attach();
    addTasks(streamCtrl);
  }).thenExpect('pager at page 1', () {
    return {
      taskList.currentPageNo: 1,
      taskList.backwardPaginationDisabled: isFalse
    };
  }).then('go to page 2', () {
    taskList.nextPage();
    addTasks(streamCtrl, count: 1);
    cursorPageNo = 1;
  }).thenExpect('pager unchanged', () {
    return {
      taskList.currentPageNo: 2,
      taskList.backwardPaginationDisabled: isTrue
    };
  });
});
```
