### ISSUE TITLE
Unnecessary breaks in arithmetic expressions 

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/dart_style#199]
I'm not sure what the correct behavior would be here, but the following does not sem right and is hard to read:

```
    final monitorTimeout = (utcTime.millisecondsSinceEpoch +
            3 * Duration.MILLISECONDS_PER_MINUTE) /
        1000;
```

1. The divisor can actually fit on the second line after the slash
2. If it must wrap to then it seems it should be indented the same as the previous line.

**Comment by munificent** [comment]
> 1\. The divisor can actually fit on the second line after the slash

Indeed. I actually don't mind that it splits here because it makes it clearer that there is that hanging operand and it doesn't get lost at the end of the line.

But, in general, there is some unintended behavior in the formatter here. In particular (this is mostly just a note to myself), it uses multisplits for operators. That means any inner split forces all outer nested operators to also split. I don't know if that's what we want.

> 2\. If it must wrap to then it seems it should be indented the same as the previous line.

This is deliberate. The formatter ensures different levels of nesting get different levels of indentation in a wrapped statement. If they were given the same:

```dart
    final monitorTimeout = (utcTime.millisecondsSinceEpoch +
        3 * Duration.MILLISECONDS_PER_MINUTE) /
        1000;
```

Then it's too easy to visually parse that wrong. The divsion applies to the previous two lines, not just the second one. Giving `1000` different indentation highlights that.

**Comment by munificent** [comment]
After some further thought and lots more tests that touch this behavior, I do think forcing an operator to split if its operands contain a split is the best thing to do here. It helps clarify the precedence levels, which is important for reading code using mixed operators.
