### ISSUE TITLE
Long strings for named arguments should indent 4 spaces on newlines

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#220]
Started with this:

```
expect(b, 0, reason:
    'we pick the "package:" url as the canonical url for script tags.');
```

Formatter turned it into this:

```
expect(b, 0,
    reason: 'we pick the "package:" url as the canonical url for script tags.');
```

So I split the String up to fix the >80 character issue:

```
expect(b, 0,
    reason: 'we pick the "package:" url as the canonical url for script '
        'tags.');
```

Ran the formatter again and it did this:

```
expect(b, 0,
    reason: 'we pick the "package:" url as the canonical url for script '
    'tags.');
```

While not ideal, I would be ok with where I ended up if at least 'tags.' remained indented.

**Comment by munificent** [comment]
In the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253), this code gets formatted as:

```dart
    expect(
      b,
      0,
      reason:
          'we pick the "package:" url as the canonical url for script tags.',
    );
```

If I indent it farther so that the string still doesn't fit and then split the string, I get:

```dart
      expect(
        b,
        0,
        reason:
            'we pick the "package:" url as the canonical url for script '
            'tags.',
      )
```

That looks pretty good to me. (Well, the `b` and `0` lines look a little sparse, but arguments that short are sort of outliers.)
