### ISSUE TITLE
dartformat --dry-run should have exitCode != null when there are files which would be modified

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#225]
I try to create a grinder task which checks as many aspects of my project as possible and one of these is whether the source is properly formated.

`dartformat --dry-run .` writes a list of files to the output but it isn't supported (yet) in grinder to get stdout/stderr output when the task is run as `pub global run ...` 
(which I try to use instead of importing, see also #215, and which also allows to get rid of additional dependencies ;-) ).

So exiting with 1 instead of 0 when there are files which need update would be great.

**Comment by munificent** [comment]
I considered this, but after talking with some people, we decided the current behavior is probably the least surprising. The problem is that we ideally need different exit codes that all mean "success", and exit codes don't really let you express that.

When you run the formatter *without* `--dry-run` it exits with zero whether or not it did work, as long as it didn't encounter any errors. I believe that's the right behavior.

I think it will confuse people if `--dry-run` then has a different set of exit codes. So, the answer we came up with is that you have to see if it produced any output to tell if it made changes or not.

**Comment by zoechi** [comment]
I just want a way to get a different exitcode depending whether all files are properly formatted. How can I achieve that?
