### ISSUE TITLE
Format expressions within string interpolation

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#226]
``` dart
'Bad Request${(detail!='' ? ': ' : '')}$detail'
```

should be

``` dart
'Bad Request${(detail != '' ? ': ' : '')}$detail'
```

**Comment by munificent** [comment]
Ugh, I knew someone was going to ask for this. :)

It's a rathole, but at the very least it should probably fix up whitespace.

**Comment by zoechi** [comment]
At least such simple ifs should be supported. More complex expressions are usually calculated outside the string. I find it annoying for example to create a block body for a function instead of `=>` for such a simple case.

**Comment by munificent** [comment]
I did some more poking around at this based on @BlackHC's PR, but wasn't able to find any straightforward way to get it working. The problem is basically:

1. We likely *don't* want to add soft splits inside an interpolated string. In most corpus's I've looked at, it looks much better to just let the line run long than add a newline in the middle of the interpolation.

2. But we don't want to disable *all* newlines either. Hard lines (think a function literal inside an interpolation) should certainly be preserved. And the user's hand-authored ones maybe.

So that leads us towards some weird mode where newlines are handled really idiosyncratically inside interpolation. It might be tractable, but I don't think it will be simple.

**Comment by nex3** [comment]
I'd like to +1 this at least for cleaning up whitespace. I have a simple transform to get rid of calls to `await`, and I'm ending up with a lot of strings that look like `"(${ expression})"`, with an extra space after the beginning of the interpolation. Whitespace outside the expression seems like a pretty trivial case to clean up, and one that will help a lot of simple transformations like the one I'm doing.
