### ISSUE TITLE
Function passed into .then not indented enough

### ISSUE THREAD

**Issue by rkj** [dart-lang/dart_style#237]
```
  void foo() {
    blah.method(someLongArgument, andAnotherOne, andAThirdOne, andOneMore)
      .then((var x) {
        var y = x * 2;
      });
  }
}

```
gets formatted into:
```
class Bar {
  void foo() {
    blah
        .method(someLongArgument, andAnotherOne, andAThirdOne, andOneMore)
        .then((var x) {
      var y = x * 2;
    });
  }
}
```
not sure why .method is moved to another line, but the var y is not indented as I would expected.

**Comment by munificent** [comment]
This is working as intended. Function literals that are passed as arguments often get formatted as "block arguments", which means they are indented almost as if they were `{}` bodies in a control flow statement.

It looks funny on short functions sometimes, but it's really helpful on large functions to avoid wasting a lot of dead space on the left. In other words, this:

```dart
object.method(() {
  body;
  body;
  body;
  body;
  body;
});
```

instead of:

```dart
object.method(
    () {
      body;
      body;
      body;
      body;
      body;
    });
```

> not sure why .method is moved to another line

If a chain of method calls doesn't fit on one line, they each get moved to the next, including the first. It looks weird here because the receiver `blah` is really short, but in normal code, it nicely lines up all of the method calls:

```
class Bar {
  void foo() {
    someLongerObjectName
        .method(someLongArgument)
        .method(andAnotherOne)
        .method(andAThirdOne)
        .method(someLongArgument, andAnotherOne, andAThirdOne, andOneMore)
        .then((var x) {
      var y = x * 2;
    });
  }
}
```

**Comment by rkj** [comment]
This makes it a really hard sell for the formatter. I have never before seen a case where something semantically nested is indented less than the parent.
For your example, of course the first one looks better, the second case looks also good, while the formatter would create (assuming breaking on the first line that it doesn't do):
```
object.method(
    () {
  body;
  body;
    });
```
Don't you think it looks really odd?

**Comment by zzzev** [comment]
+1 to rkj's point of view, I think the formatter's version feels unconventional and less readable than the one that uses semantic indentation.

**Comment by siggisim** [comment]
+1

**Comment by munificent** [comment]
> I have never before seen a case where something semantically nested is indented less than the parent.

Consider:

```dart
if (longCondition ||
    thatWrapsToTheNextLine) {
  indented(2);
}
```

The behavior the formatter has for collections and functions matches that. It helps to think of "block arguments" like this as being conceptually outside of the argument. For example, if this were Ruby, instead of:

```ruby
items.select(Proc.new begin
  |n| n*factor
end)
```

you would do:

```ruby
items.select begin
  |n| n*factor
end
```

Dart doesn't actually have block arguments (alas), but it's very common to have code that passes functions or collections to methods in a way that acts like it does. The formatter tries to format those in a reasonable way.

If it didn't, you'd get way too much indentation. For example, here's a bit of the formatter's unit tests:

```dart
group('line endings', () {
  test('uses given line ending', () {
    expect(new DartFormatter(lineEnding: "%").format("var i = 1;"),
        equals("var i = 1;%"));
  });

  test('infers \\r\\n if the first newline uses that', () {
    expect(new DartFormatter().format("var\r\ni\n=\n1;\n"),
        equals("var i = 1;\r\n"));
  });

  ...
});
```

If we always formatted functions like regular arguments, that would be:

```dart
group(
    'line endings',
    () {
      test(
          'uses given line ending',
          () {
            expect(new DartFormatter(lineEnding: "%").format("var i = 1;"),
                equals("var i = 1;%"));
          });

      test(
          'infers \\r\\n if the first newline uses that',
          () {
            expect(new DartFormatter().format("var\r\ni\n=\n1;\n"),
                equals("var i = 1;\r\n"));
          });

      ...
    });
```

> For your example, of course the first one looks better, the second case looks also good, while the formatter would create (assuming breaking on the first line that it doesn't do):
>
> ```dart
object.method(
    () {
  body;
  body;
    });
```

The formatter won't produce this. It will do either:

```dart
object.method(
    () {
      body;
      body;
    });
```

or

```dart
object.method(() {
  body;
  body;
});
```

The choice between the two depends on what else is in the argument list that contains the function. If it's just a function by itself, you'll usually get the latter unless the surrounding expression affects it.

**Comment by rkj** [comment]
And how about:
```
tools = treeNodes.map((node) => new TableRowToolsController(null)..initialize(selectionModel, root, node)).toList();
```
being formatted into:
```
      tools = treeNodes
          .map((node) => new TableRowToolsController(null)
        ..initialize(selectionModel, root, node))
          .toList();
```
?

**Comment by munificent** [comment]
That was a bug. It's fixed now. See: https://github.com/dart-lang/dart_style/commit/61e60cb7bae493220f1e48a5d7a0110300a01a17
