### ISSUE TITLE
dartfmt violates go/java-practices-line-breaks

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/dart_style#239]
See go/java-practices-line-breaks.
I know it has Java in the name but it's good practice in any language.
Basically, line breaks should happen at the higher syntactic level. Not just where they make the line as long as possible while still staying under 80 characters.
I try to follow this practice in my code and running dartftm ruins this, making the code less readable.

**Comment by zoechi** [comment]
Do you have a concrete example?

**Comment by dskloetg** [comment]
Do you have access to code inside Google?

**Comment by zoechi** [comment]
Me not but I assume Bob has.

**Comment by dskloetg** [comment]
Bob can have a look at lines 59, 94, 195, 281 and 366 in go/dskloet-dartfmt.

**Comment by munificent** [comment]
> Basically, line breaks should happen at the higher syntactic level.

Alas, ideal formatting isn't that simple. That rule is *basically* correct, but when you look carefully at even your hand-formatted examples, you'll find that isn't the rule you're always following.

The formatter has a similar but slightly more complex way of expressing this which is that it tries to minimize the number of regions that contain a line break. Since regions may nest, the end result is usually that splits occur at higher levels. But, since the formatter is a constraint solver, that isn't always strictly the case: splitting at a lower level may let it avoid other more expensive splits.

That being said, some of the formatter output does look a bit wrong in your CL.

The line numbers you mention don't seem accurate any more. Could you file separate bugs for the output you don't like and I'll triage them separately? If you could include before/after code samples directly in the bug, that would help. You can just replace the identifiers with nonsense ones to keep the code private.

Thanks!

**Comment by dskloetg** [comment]
I understand it's not always easy to do the right thing, but do you think it makes sense to simply not change the code when there's a chance that what's there is better than what the formatter would replace it with?

**Comment by munificent** [comment]
> do you think it makes sense to simply not change the code when there's a chance that what's there is better than what the formatter would replace it with?

The problem is how does the formatter decide which code has this chance? I don't think there's any simple way to determine which code intentionally differs from the formatter's output from that which doesn't.

**Comment by dskloetg** [comment]
One way is when the lines don't exceed 80 and the indentation is correct, just don't change the line.
