### ISSUE TITLE
Support --version

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_style#240]

**Comment by sigmundch** [comment]
+1

**Comment by munificent** [comment]
I'd like to do this, but I don't want to duplicate the version number in the pubspec and elsewhere in order to print it. The right thing to do is have the formatter just read its own pubspec and parse the version from there.

However, you can't actually reliably do that in pub run yet. Once the resource API stuff is done, this should be doable.

**Comment by seaneagan** [comment]
I assumed the `const Resource('package:dart_style/pubspec.yaml')` would actually reference `lib/pubspec.yaml` i.e. the wrong location.  I was envisioning https://github.com/dart-lang/pub/issues/1154 as the solution to this.

**Comment by munificent** [comment]
Hmm, that's a good point. The Resource API may not help. :(

**Comment by sethladd** [comment]
FWIW in dartdoc we simply put a const String for version into the library. We then have a grinder task that updates both that string and the pubspec.yaml and another grinder task that checks they are both consistent before publishing :)

**Comment by munificent** [comment]
Yeah, I thought about that, but I was hoping to have to avoid tooling it like that.

**Comment by sethladd** [comment]
I know this is on your long-term plan, but FWIW we just had a mixup between our buildbots, the dartfmt that comes with the SDK, and the dartfmt that you can install directly with pub global activate. Because users can easily have two versions of dartfmt on their path, having a --version can help diagnose just what version is being run. :)

**Comment by sethladd** [comment]
Super cool, thanks!
