### ISSUE TITLE
Should line split between metadata annotations and parameter

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_style#387]
The formatter seems to split between annotations and the declarations they annotate in most cases:

```
@Foo
int foo;
```

...but not for parameters.

Actual (as of e845f631cb9d2f5c5011e0ede186a3aea662ae77):

```dart
greet(@Rest(valueHelp: 'who', help: 'Name(s) to greet.') List<String> who,
    {@Group.start(title: 'Output')
    @Option(help: 'How many !\'s to append.')
    int enthusiasm: 0,
    @Flag(abbr: 'l', help: 'Put names on separate lines.') bool lineMode: false,
    @Option(name: 'greeting', help: 'Alternate word to greet with e.g. "Hi".')
    String salutation: 'Hello'}) {}
```

Expected:

```
greet(
    @Rest(valueHelp: 'who', help: 'Name(s) to greet.')
    List<String> who,
    {@Group.start(title: 'Output')
     @Option(help: 'How many !\'s to append.')
     int enthusiasm: 0,
     @Flag(abbr: 'l', help: 'Put names on separate lines.')
     bool lineMode: false,
     @Option(name: 'greeting', help: 'Alternate word to greet with e.g. "Hi".')
     String salutation: 'Hello'}) {}
```

(The rest of the differences are are accounted for in #386.)

**Comment by munificent** [comment]
The output is deliberate here. Since the whole `who` parameter, including its metadata, fits on the first line, it leaves it like that.

It might be possible to tweak it so that all metadata annotations get split if anything in the parameter list goes multiline, but that gets kind of hairy and I feel like we're reaching the point of diminishing returns here. Maybe it's just me, but I think the actual output looks OK here.

**Comment by seaneagan** [comment]
> The output is deliberate here. Since the whole who parameter, including its metadata, fits on the first line, it leaves it like that.

From my (limited) testing the formatter *does* split between metadata annotations and that which they annotate for every other type of metadata target (besides parameters), for example:

```dart
@Foo()
int foo;

@Bar('x', 'y', 'z', baz: const [1, 2, 3])
String bar() {
  // ...
}
```

which is much more readable than:

```dart
@Foo() int foo;

@Bar('x', 'y', 'z', baz: const [1, 2, 3]) String bar() {
  // ...
}
```

since everything is lined up to start at the same column.  And its much easier to copy/cut/paste those metadata around (a common task with metadata annotations) since they're on their own line.

So why not afford metadata annotated parameters with those same advantages?

> It might be possible to tweak it so that all metadata annotations get split if anything in the parameter list goes multiline,

I'd want a metadata annotation on a parameter to cause the one-parameter-per-line strategy to go into effect, at least for that sub-group of parameters (required or positional, see #386).

> Maybe it's just me, but I think the actual output looks OK here.

The formatter is amazing!  It's just that metadata annotations on parameters are a fairly common pattern for me (and users of my libraries), hence the interest in improving the output here.

**Comment by munificent** [comment]
> From my (limited) testing the formatter does split between metadata annotations and that which they annotate for every other type of metadata target (besides parameters)

That's right. Parameter metadata is treated differently from declaration metadata.

> I'd want a metadata annotation on a parameter to cause the one-parameter-per-line strategy to go into effect

I think that would look good for your libraries where you tend to have a lot of big heavy annotations on parameters. But in other cases, it's just a single `@deprecated` or something like that on a single annotation. Forcing that whole parameter list to go multi-line would probably be the wrong choice.

> It's just that metadata annotations on parameters are a fairly common pattern for me (and users of my libraries), hence the interest in improving the output here.

I didn't have much of a sample set to look at when I implemented this since parameter metadata isn't very common. I'll re-open this. When I get a chance, I'll grep through some packages to see where parameter metadata is being used and go from there.
