### ISSUE TITLE
Weird formatting with generic field and line comment

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#403]
```dart
UnmodifiableMapView<String, UnmodifiableListView<String>> _mountPoints; // TODO check generic type with actual data
```
becomes
```dart
UnmodifiableMapView<
      String,
      UnmodifiableListView<
          String>> _mountPoints; // TODO add generic type with actual data
```  

I don't know how to get the dart_style version.
I use Dart VM version: 1.13.0-edge.3851c8c0eda48907649193d475737e87192eeee5 (Thu Aug 13 16:24:09 2015) on "linux_x64

**Comment by zoechi** [comment]
Seems not related to the comment. Another example

```dart
  UnmodifiableMapView<String, UnmodifiableMapView<String, String>> _exposedPorts;
  UnmodifiableMapView<String, UnmodifiableMapView<String, String>> get exposedPorts =>
      _exposedPorts;
```

becomes
```dart
UnmodifiableMapView<String,
      UnmodifiableMapView<String, String>> _exposedPorts;
  UnmodifiableMapView<String,
      UnmodifiableMapView<String, String>> get exposedPorts => _exposedPorts;
```
I hope this is not intentional. Looks like a mess.

**Comment by munificent** [comment]
Oh, yeah. Those definitely aren't ideal.

**Comment by munificent** [comment]
Looking more closely, these are working as intended.

The formatter will try its hardest to get a line to fit, but it will not move line comments to the next line. Since that makes the line very long, it adds all the splits it can—in the type arguments—to get it to fit. You should probably just move the line comment to the previous line.

Likewise, in the second example, the declarations don't all fit on one line, even if you split after the `=>`. The only choice it has is to split at the type argument. (I suppose we could support splitting before or after `get` but I think that will be less readable in almost all cases.)

You just have a really long type annotation. There's no magic wand that can fix that. :(
