### ISSUE TITLE
Insufficient indentation for directives const arrays

### ISSUE THREAD

**Issue by bernardyen** [dart-lang/dart_style#412]
Given the original input

```
@View(
    directives: const [
      MaterialButtonDropdownComponent,
      MaterialListComponent,
      MaterialListItemComponent
    ])
```

dartfmt will convert it into

```
@View(
    directives: const [
  MaterialButtonDropdownComponent,
  MaterialListComponent,
  MaterialListItemComponent
],
```

This is not correct because the 3 items inside the const array are continuations of the const [ line and not part of the @View statement, which this indentation implies.

**Comment by munificent** [comment]
This is working as intended. In many cases, collection and function bodies are indented relative to the containing statement, not expression.

(This comes up all the time. I really need to write a detailed FAQ entry about it...)

**Comment by bernardyen** [comment]
I guess I don't understand why the collection in this case would be indented relative to the containing statement. This would seemingly imply that collections in functions should always break out. For example

```
void main() {
  var a = new B(
      new C(
          new D([
    item1,
    item2,
    item3,
  ];
```

which doesn't seem right to me. Why are we not indenting to the collection if the items are associated with the collection?

**Comment by munificent** [comment]
They don't *always* break out, but they often do. It's a trade-off. I'm trying to balance not adding extra indentation that's wasteful on large collections and functions while still making the indentation helpful otherwise.

I'm going to try to play with the rules it uses to choose between the two and see if I can come up with something better. I think it's important to be aggressive about indented relative to the statement for function bodies, but probably less so for collections.
