### ISSUE TITLE
Incorrect indentation for => returning arrays

### ISSUE THREAD

**Issue by bernardyen** [dart-lang/dart_style#413]
When I run dartfmt on

```
List get bindings => [
    bind(const StaticFilePath())
        .toValue(_staticFilePath.isEmpty ? _libRoot : _staticFilePath)
  ];
```

I get

```
List get bindings => [
        bind(const StaticFilePath())
            .toValue(_staticFilePath.isEmpty ? _libRoot : _staticFilePath)
      ];
```

This doesn't seem right. The "]" is matching the "[" on the =>, which should then go all the way back to the left margin. Instead, dartfmt seems to want to add additional indentations.

**Comment by munificent** [comment]
I can't reproduce the output you have here, but I suspect your input isn't exactly what's in the bug. Is this getter supposed to be inside a class definition? You have the first line full left justified.

What it *should* be doing, and is on my machine, is indenting the list +4 relative to the first line, and then the body is another +2 on top of that.

It's +4 because of the `=>`. We indent multi-line expression-bodied members like expressions because (1) they are and (2) it avoids very hard to read code when the body is a map literal:

```dart
List get bindings => {
  "this looks like": "a regular curly body"
};
```
