### ISSUE TITLE
Support splitting string literals

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/dart_style#431]
For me this especially occurs in test code where the description/name string in a test method if often longer than the line length. It would be very nice if the formatter could split such strings.

```dart
testThat('something totally awesome and beyond your wildest dreams happens when the big green button is clicked',
      when: (dom.Element element, Scope scope) async {
  // Click green button and assert the awesome thing happened
}
```

**Comment by munificent** [comment]
Splitting string literals, while it would be handy in many cases, is out of scope for the formatter. [This FAQ entry](https://github.com/dart-lang/dart_style#why-doesnt-the-formatter-add-curlies-or-otherwise-clean-up-code-then) touches on why a bit.

More specifically, with strings, it's important that the formatter never make an irreversible change. Let's say you have some code like this:

```dart
function(someArgument, "a fairly long but not overly long string literal here");
```

Now you rename `someArgument` to `someMuchLongerArgument`. The string no longer fits. So the formatter splits the string for you:

```dart
function(someMuchLongerArgument, "a fairly long but not overly long string lit"
    "eral here");
```

(I'll ignore the also nasty problem of deciding *where* to split.) Now you decide to change the argument name *back* to `someArgument`. That *should* get you back to your original code, but it won't, because the string is split now.

The formatter is very unlikely to automatically *join* adjacent strings because that would likely do the wrong thing in the many cases where a user split those strings deliberately.
