### ISSUE TITLE
library declarations not line broken if they exceed 80 cols

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#440]
Library declarations not line broken if they exceed 80 cols.

```dart
library this_name.is_very.long.because.my.company.likes.to.nest.code.in_very.deep.directories;
```

By hand I can fix this up as:
```dart
library this_name.is_very.long.because.my.company.likes.to.nest.code.in_very.
    deep.directories;
```

but the formatter won't respect this, in fact it will remove the newline, making the line longer than 80 col

**Comment by munificent** [comment]
Oh, wow.

I'm going to close this out because I don't think I intend to do anything different here. This is an unusual case and I think it's probably better to remain on one long line than split it.

Also, soon library tags will be optional and, unless you are using `part`, I expect people to start deleting them entirely.
