### ISSUE TITLE
assignments that have a single cascading assignment get all formatted to one line

### ISSUE THREAD

**Issue by ninabikes** [dart-lang/dart_style#479]
This is better explained with an example.

``` dart
// Expected result
var foo = new Foo()
  ..bar = bar;

// Actual result
var foo = new Foo()..bar = bar;
```

I find the current behavior to be harder to read, as it has two assignments on a single line, and it takes slightly more mental effort to parse what is being assigned to what.

When there is more than one cascading assignment, the formatter behaves as expected.

``` dart
var foo = new Foo()
  ..bar = bar
  ..baz = baz;
```

**Comment by munificent** [comment]
This is working as designed. The formatter allows a single cascade on one line, independent of the context of where that cascade appears. Using the surrounding context to affect this, I think, would open a can of worms.

I agree that the example is hard to read, but I think that says more about the cascade syntax than the formatter. In this case, I would just not use a cascade.

**Comment by ninabikes** [comment]
> In this case, I would just not use a cascade.

Do you mean like
```dart
var foo = new Foo();
foo.bar = bar;
```
or something else? It seems odd not to use a cascade here.

**Comment by munificent** [comment]
Yup, exactly.

The other thing is that in my code I would almost never need to call a setter right after constructing. Instead, that would be a constructor parameter. But I'm guessing you probably run into this dealing with protobuf-generated classes?

**Comment by ninabikes** [comment]
> But I'm guessing you probably run into this dealing with protobuf-generated classes?
Yes.

Behavior noted. Will probably continue to use cascades even in the case of a single setter, since it'll be consistent.

**Comment by xavierhainaux** [comment]
I would like to add my vote here. I don't like the current behaviour neither. It seems arbitrary to me to have a distinction between 1 assignment and more than 1.
I think there are lot of use-cases where you want to configure a newly created object with a setter. You can't have all the properties as named parameter on the constructor.

I would vote for "always put the cascade on a new line whatever the surrounding context is".

Just an opinion :-)

**Comment by munificent** [comment]
> I would vote for "always put the cascade on a new line whatever the surrounding context is".

That was the original behavior I implemented but I got a lot of pushback from users.

The problem is that if you require *every* cascade to be two lines, it starts to defeat the purpose of the cascade syntax. Note that in Nina's original example, the multi-line version is exactly as long as not using a cascade at all.

If it were me, I would definitely put them on their own line every time, but, then, if it were me, I would have picked a better syntax for cascades to begin with. They are hard to format because if you don't format them *just* right, they become completely unreadable. Case in point:

```dart
point..x = 1..y = 2;
```

**Comment by ninabikes** [comment]
I am glomming this question onto this bug although this might be slightly different:

If I have multiple non-assignment cascades, they are all formatted onto the same line if they fit within 80 characters. Otherwise, each cascade gets its own line. Is this also intended?

**Unexpected behavior**
```dart
var foo = <String>[];

// Before: fits within character limit
foo..add('this is a longish string')..add('this is a longish string');

// After: unchanged
foo..add('this is a longish string')..add('this is a longish string');
```
**Expected behavior**
```dart
var foo = <String>[];

// Before: exceeds character limit
foo..add('this is a longish string')..add('this is a longish string')..add('this is a longish string');

// After: each cascade gets its own line
foo
  ..add('this is a longish string')
  ..add('this is a longish string')
  ..add('this is a longish string');
```

**Comment by munificent** [comment]
> If I have multiple non-assignment cascades, they are all formatted onto the same line if they fit within 80 characters.

The formatter allows multiple cascades on one line if and only if:

1. They are all method calls.
2. For the *exact same method*.

I don't like it either, but @jacob314 pushed for it and implemented it. If you can convince him to change his mind, or get feedback from other people, I would be happy to change this back.

**Comment by jacob314** [comment]
I'm not convinced. While the two options are a coin toss for:
foo..add('this is a longish string')..add('this is a longish string');
I think
foo..add(bar)..add(baz)
is much better than
foo
  ..add(bar)
  ..add(baz)

**Comment by ninabikes** [comment]
> 2. For the exact same method.

Oh, I'm not a fan of this as it sounds like unnecessary special-casing and is not at all clear just looking at the output of the formatter (vs. the implementation).

FWIW, I think the particular likelihood of fulfilling all of these cases

1. all method calls
2. all exact same method
3. fits within 80 character limit

is so rare that that's why I hadn't even come across it until recently.

my 2c. :)

**Comment by munificent** [comment]
I think this basically only really comes into play with StringBuffer. Personally, in that case I'm more likely to either not use cascades, or do:

```dart
buffer.addAll([bar, baz]);
```

**Comment by greglittlefield-wf** [comment]
I agree that having all of these on one line is unexpected behavior as a user. 

It's confusing to see these cascades formatted differently, and not clear why they're formatting differently.

Also, for most of the use-cases I've run into, the result is less readable than if the cascades were on their own lines. Here are some examples I hit when formatting a previously-unformatted repo with dartfmt for the first time:
```dart
// Expected
var classes = forwardingClassNameBuilder()
  ..add('grid-block')
  ..add('ribbon-action-toolbar');

// Actual
var classes = forwardingClassNameBuilder()..add('grid-block')..add('ribbon-action-toolbar');
```
```dart
// Expected
_actions
  ..insert.listen(_insert)
  ..delete.listen(_delete)
  ..editable.listen(_makeEditable);

// Actual
_actions..insert.listen(_insert)..delete.listen(_delete)..editable.listen(_makeEditable);
```
Granted, the repo uses a line-length of 120 (partly due to some Java-esque naming, but mostly because of the amount of tests with long descriptions and a good deal of nesting), so I'm experiencing the problem more often than if had I used the default 80.

**Comment by munificent** [comment]
> ```dart
> var classes = forwardingClassNameBuilder()
>   ..add('grid-block')
>   ..add('ribbon-action-toolbar');
> ```

This is working as intended. If you have a cascade where every method has the same name, it allows them to pack on one line. I'm not personally a fan of this style, but when I implemented cascades, it was something a number of users felt was important.

> ```dart
> _actions..insert.listen(_insert)..delete.listen(_delete)..editable.listen(_makeEditable);
> ```

That's a bug. It shouldn't treat these as being a series of calls to `listen()` since each is a call on a different getter. Reopening this to fix that.
