### ISSUE TITLE
Unexpected indentation of bracket-less `for` statements

### ISSUE THREAD

**Issue by elaru** [dart-lang/dart_style#498]
Hey!

I stumbled upon this today and wondered whether it is intended. This is how `dartfmt` formats the following code:
```Dart
void the_name_of_this_function_is_longer_than_sixty_characters(p) {}

main() {
  if (true)
    for (var i in [])
      for (var j in [])
        the_name_of_this_function_is_longer_than_sixty_characters(i + j);

  if (true)
    for (var u in [])
      for (var v in []) {
    the_name_of_this_function_is_longer_than_sixty_characters(u + v);
  }
}
```
The body of the `j` loop is a single expression statement and gets indented correctly. But compare it with the body of the `v` loop, which is a compound statement: both the child statements and the closing bracket are indented as if they belonged to the `if`. Is that the intended behaviour?

Best regards,
Philipp

**Comment by munificent** [comment]
It depends on what you mean by "intended". :) This is a natural consequence of how it formats braced statements and multi-line statements without braces. So in that sense the output is unsurprising to me and is, I guess, intentional.

But did I have code like this specifically in mind? No. I think most people would not nest multiple multi-line statements, and I certainly hope most wouldn't nest a multi-line statement with a block body within one that didn't have one.

This code violates the style guide, so the formatter isn't really obligated to do a great job on it. I think the output it produces is reasonable.
