### ISSUE TITLE
Bad formatting of very long return type

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#503]
Output:

```dart
class Foo {
  Stream<
      api
          .ReallySuperExtremelyLooooooongTypeName> veryExtremelyLoooongMethodName(
      String parameter, int parameter2, String thirdParameter) {
    ;
  }
}
```

Desired:

```dart
class Foo {
  Stream<api.ReallySuperExtremelyLooooooongTypeName>
      veryExtremelyLoooongMethodName(
          String parameter, int parameter2, String thirdParameter) {
    ;
  }
}
```

**Comment by mezoni** [comment]
Main rules here maybe the following:
- Never divide the `type` into the chunks (even it does not fit into line). Very long type (with all generic arguments) is a problem of the programmer but not a problem of the formatter.
- If `type` (return in our case) + delimiter+ function name does not fits then move a function name at the next line. This work is done. Goto formatting function arguments.

Formatting function parameters:

```dart
Type func(
  int ifParametersDoesFitIntoSingleLine,
  int param2) { 
```
This pair ') {' always should be after the last parameter declaration even if it this line (with parameter declaration) does not fit.
It is a problem of the programmer (very long pair of type + parameter) but not a problem of the formatter.

The main thing of the formatter is not in that the `prevent exceed line limit`.
The main thing of the formatter is two things:
- Made code more readable
- Fit into the line limit as much as possible a source code lines but not fanatically every line.

P.S.

Formatting a function parameters (in declaration) and formatting a function arguments (in function invocation) is not the same thing only because they are different parts of the program and are perceived (by the programmer) differently.

Formatter is not minifier (line limit bounds).
Formatter is source beautifuler (for humans and for readability).

**Comment by mezoni** [comment]
I have great doubt that this software will ever properly do their job in the future.
Bob, this is the worst of your programs that you have ever written.
I call it as a silly formatter.
