### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/dart_style#508]
So I worked a bit with Go again last week and one thing I really like is the automatic vertical alignment from the Go formatter like in this example snippet:

``` go
categoryHeader := WidgetCategoryHeader{
    Type:           "categoryheader",
    Title:          GetTranslation(categoryData, person.Language, "Name").(string),
    HeaderBgColor:  categoryTheme.HeaderBgColor,
    HeaderColor:    categoryTheme.HeaderColor,
    HeaderImageUrl: categoryData.ImgUrl,
}
```

Below is a snippet from one of my Dart projects:

``` dart
return new SnippetSelector(data['class'] as String,
  database: data['database'] as String,
  table: data['table'] as String,
  all: data['all'] as bool,
  attributes: data['attributes'] as Map<String, String>,
  parameters: data['parameters'] as Map<String, String>);
```

Now with some vertical alignment it could look like this:

``` dart
return new SnippetSelector(data['class'] as String,
  database:   data['database']   as String,
  table:      data['table']      as String,
  all:        data['all']        as bool,
  attributes: data['attributes'] as Map<String, String>,
  parameters: data['parameters'] as Map<String, String>);
```

I certainly like this much better than the previous snippet. It makes certain parts of my code look much cleaner. A Map could be aligned the same way.

``` dart
Map<String, dynamic> map = {
  'one':      1,
  'ten':      10,
  'hundred':  100,
  'thousand': 1000
}
```

`dartfmt` is part of the pre-commit hook in all my Dart projects (and I've never been so happy!), but hand formatting for this kind of cases is impossible.

I realize that this feature might be very difficult to implement. And probably not everyone agrees vertical alignment is a good thing. Even more so because `dartfmt` is not configurable, and changing this would mean everyone's code gets vertical alignment. The vertical alignment step could also be a 'post-processing' tool that you can run after `dartfmt`.

Anyway, I could not find an issue mentioning this subject.

**Comment by munificent** [comment]
Yeah, it's good to have a tracking issue for this. Like you note, yes, it's very difficult to implement. gofmt doesn't do line breaking, so vertical alignment is a much simpler problem for it. :)

It's a deliberate choice in dartfmt to *not* do vertical alignment because:

* It's very complex to implement.
* Assuming you can implement it, it may be very slow.
* It's not obvious what the rules for which things to align should be.
* It's not clear that the end result will always be an improvement. It may be unpleasantly surprising to users when it does or does not align and which things it chooses to align.
* It tends to make diffs bigger when nearby lines get realigned.

All of that means that it's unlikely for dartfmt to support this any time soon, if ever. But it's never been officially taken off the table either, so it's good to have an issue hanging around.

**Comment by munificent** [comment]
OK, it's five years later and I think it's time to take vertical alignment off the table. I'm not morally opposed to it, but it would require a wholesale redesign of the formatter and it's not at all clear that the result would be an improvement.
