### ISSUE TITLE
dartfmt should respect existing line breaks.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/dart_style#586]
I have import declarations like this:

```
import 'package:kernel/class_hierarchy.dart' show
    ClassHierarchy;

import 'package:front_end/src/fasta/scanner/token.dart' show
    BeginGroupToken,
    Token,
    isBinaryOperator,
    isMinusOperator;

import '../quote.dart' show
    Quote,
    analyzeQuote,
    unescape,
    unescapeFirstStringPart,
    unescapeLastStringPart,
    unescapeString;
```

If I run dartfmt on this, I get:

```
import 'package:kernel/class_hierarchy.dart' show ClassHierarchy;

import 'package:front_end/src/fasta/scanner/token.dart'
    show BeginGroupToken, Token, isBinaryOperator, isMinusOperator;

import '../quote.dart'
    show
        Quote,
        analyzeQuote,
        unescape,
        unescapeFirstStringPart,
        unescapeLastStringPart,
        unescapeString;
```

Moving several show items to the same lines makes it harder to add new, and will create a noisier diff.

Similarly, consider this statement:

```
      return new ConstructorInvocation(target, arguments)
          ..isConst = isConst;
```

Dartfmt rewrites it to:

```
      return new StaticInvocation(target, arguments)..isConst = isConst;
```

In opinion, and other people that have reviewed my code in the past, it's often important to put cascades on their own line. The reason for that is that they're often considered additional statement, and we like have one statement per line.

Another example of not respecting existing line breaks:

Original code:

```
      body = combineStatements(
          new ExpressionStatement(
              lvalue.buildAssignment(
                  new VariableGet(variable), voidContext: true)),
          body);
```

Becomes:

```
      body = combineStatements(
          new ExpressionStatement(lvalue
              .buildAssignment(new VariableGet(variable), voidContext: true)),
          body);
```

Here an important part `lvalue.buildAssignment` is broken up over two lines and it becomes harder to see that we're building an assignment of an `lvalue`.

Generally, what I don't understand about all these changes is:

I don't see a reason for any of these adjustments, because there were no lines weren't longer than 80 characters, so they didn't need to be reformatted.

What I would like to see is that the formatter is able to leave code alone that's already formatted. For example, I could imagine that the formatter could keep track of formatting issues in a statement, and can decide not to rewrite it as long as there are no issues.

**Comment by munificent** [comment]
```dart
import 'package:front_end/src/fasta/scanner/token.dart'
    show BeginGroupToken, Token, isBinaryOperator, isMinusOperator;

import '../quote.dart'
    show
        Quote,
        analyzeQuote,
        unescape,
        unescapeFirstStringPart,
        unescapeLastStringPart,
        unescapeString;
```

There's two pieces here:

1. Putting `show` at the end of the previous line instead of the beginning of the next line.
2. Putting each shown name on its own line even when they would fit on the import line.

For 1, that's a deliberate choice of the formatter. It helps ensure that when you scan down the left side of the, you can easily tell if the list of names is for a `show` clause, a `hide` clause, or both. I think the output it produces here is good.

For 2, I believe (it's been quite a while since I implemented this) I picked that based on how I saw these clauses being used in the wild. Users do often put a couple of shown or (more commonly) hidden names on a single line.

I'm not personally strong attached to this behavior. It might be worth always making these go one-per-line. We'd have to query the community and see how they feel about the change. If enough users are in favor of it, we could make the switch.

I will note that the code in question is not very idiomatic. Most libraries — I don't remember the exact numbers, but it's something like >90% — do *not* use explicit `show` clauses. dartfmt tries to make all code look good, but when trade-offs have to be made (which is often), it prefers to make the kinds of code that is most common look the best. When most `show` and `hide` clauses only have a single name or just a couple, making them all go one per line likely doesn't optimize well for that case.

> In opinion, and other people that have reviewed my code in the past, it's often important to put cascades on their own line.

I spent a lot of time tweaking the rules for how cascades are formatted based on user feedback a while ago. I got a *lot* of pushback on the suggestion that cascades *always* get split. After all, if you never put cascades on a single line, at that point you may as well just declare a local variable and not use cascades at all.

I don't think we can change this behavior without producing worse results in the opinion of the majority of users.

> Here an important part lvalue.buildAssignment is broken up over two lines and it becomes harder to see that we're building an assignment of an lvalue.

I agree, the results aren't ideal here. This is a corner of the language (nested argument lists) that already has a ton of complexity and heuristics about formatting, so it is hard to make changes to improve some code without making other code look worse. Even so, I'm up for taking a stab at it.

Can you move this one to a separate bug so I can track it individually?

> What I would like to see is that the formatter is able to leave code alone that's already formatted.

This comes up a lot. It's a reasonable request but what you're asking for is a different tool from what dartfmt is. The formatter's job is *not* to help each individual user improve the formatting of their code to their own personal satisfaction. It is to *canonicalize* the formatting such that there is no personal human involvement whatsoever. Doing that produces a single consistent style, which ends debates over personal formatting preferences, allows people to more easily read and contribute to each other's code, and makes large scale automated code changes easier to manage.

The idea is that the benefits of a single shared style outweigh the costs of the style not meeting each of our own personal preferences.

**Comment by zoechi** [comment]
I'm usually use `show` and also prefer each identifier on its own line, because it makes it easy to delete them with a single key stroke when the analyser shows them as unused after some refactoring.

It also makes them easier to sort alphabetically, but that is usually done by the IDE when a quick fix is used to add a name to show

**Comment by munificent** [comment]
I split the lvalue one into a separate bug: #594.

I'm closing this one because I don't think there's anything else to take action on.
