### ISSUE TITLE
Non-ideal formatting on x.y.foo(...)

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dart_style#596]
We had the following lines:
```
Zone.current.scheduleMicrotask(
    Zone.current.bindCallback(callback, runGuarded: true));
```

They were changed to:
```
Zone.current
    .scheduleMicrotask(Zone.current.bindCallback(callback, runGuarded: true));
```

The original formatting feels more informative.

**Comment by escamoteur** [comment]
Perhaps this could be an option
https://github.com/dart-lang/dart_style/issues/731

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) gives you:

```dart
Zone.current.scheduleMicrotask(
  Zone.current.bindCallback(callback, runGuarded: true),
);
```

That's not the same as the original formatting, of course, because of the change to how argument lists split. But I think it looks pretty good and avoids splitting after `.current`.
