### ISSUE TITLE
Allow using URI strings in "part of" declarations

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/dart_style#615]
According to the 1.23 CHANGELOG this is now supported in the language, but dartfmt doesn't seem to be happy with it.

dartfmt 0.2.16 on the command line removes a "part of" URI from the file if I use one.

Formatting via the dart_style library seems to refuse to format files using a URI "part of" -- seen in this pull request for source_gen trying to change the generated code: https://github.com/dart-lang/source_gen/pull/138

**Comment by munificent** [comment]
No, there's work to be done in dartfmt too.

It was a mistake to put this feature in the 1.23 CHANGELOG and has since been removed: https://github.com/dart-lang/sdk/commit/9add06fe7f835ec2a95175184cdcaa3d72f7c18d. The feature hasn't officially shipped yet (in part because dartfmt doesn't support it yet).

**Comment by davidmorgan** [comment]
Got it. Thanks!
