### ISSUE TITLE
Inconsistent formatting on nearly identical lines

### ISSUE THREAD

**Issue by Lance-Inman** [dart-lang/dart_style#628]
```dart
newTransaction = await pool.prepare('insert into Transactions(Timestamp, YACID, Sender, Reciever, Message) values (NOW(), ?, ?, ?, ?)');
getYAC = await pool.prepare('select ID from Yacs where ID=? and address=?');
```

formats to 
```dart
newTransaction = await pool.prepare(
          'insert into Transactions(Timestamp, YACID, Sender, Reciever, Message) values (NOW(), ?, ?, ?, ?)');
getYAC =
          await pool.prepare('select ID from Yacs where ID=? and address=?');
```

**Comment by munificent** [comment]
I'm assuming the code in question is nested inside a function with possibly one or more levels of indentation.

In general, yes, it may format lines differently based on their length. It tries to get code as close to fitting within the column limit as possible. The first line doesn't fit because of the long string, so it splits after `(` to get as much in as it can. The second line does fit, in which case it prefers to split at the assignment to keep the argument to `prepare()` on the same line as the function name.
