### ISSUE TITLE
Dartfmt not able to parse regress_29349_test.dart

### ISSUE THREAD

**Issue by crelier** [dart-lang/dart_style#633]
See issue https://github.com/dart-lang/sdk/issues/29349 for details.

**Comment by eernstg** [comment]
As of dartfmt version 1.0.7, this issue still exists. The priority is low, however, because the common front end will take over parsing (and https://github.com/dart-lang/sdk/commit/1582021556bee80578d93cef30e2158c4934c7ae presumably adds the required fix to the common front end). Hence setting the priority to Low.

**Comment by eernstg** [comment]
Closing: `dartfmt` version 1.2.0 handles the example in #29349 and `tests/language_2/regress_29349_test.dart` correctly.
