### ISSUE TITLE
New line for annotations on parameters with trailing commas?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#653]
Almost all annotations in Dart are formatted to be on the preceding line:

```dart
@deprecated
class Foo {}

class Bar {
  @deprecated
  void bar() {}
}
```

... but not on _parameters_:

```dart
void baz([@deprecated baz]) { /* ... */ }
```

That makes sense above, sure, but seems out of place on trailing comma calls:

```dart
void baz({
  @deprecated arg1,
  @deprecated arg2,
}) { /* ... * }
```

if it makes sense to the Flutter team, I think it would make sense to format like this:

```dart
void baz({
  @deprecated
  arg1,
  @deprecated
  arg2,
}) { /* ... * }
```

/cc @yjbanov WDUT?

**Comment by yjbanov** [comment]
Makes sense for `@deprecated`, but I'm not sure about `@required`. `@required` seems to work much better on the same line, but that's probably because it works more like a modifier keyword than an annotation.

**Comment by matanlurey** [comment]
Yeah, I agree with that, generally.

I'd have to have to add special rules just for `@required`, and adding something like `@modifier` to _add_ to `class Required`, and having dartfmt understand all of that ... seems like ... a lot.

**Comment by yjbanov** [comment]
`dart_style` looks at one file at a time, so it wouldn't even know that there's a `@modifier` annotation on `class Required`.

Having said that, perhaps the rule could be if the annotation begins with a capital letter, e.g. `@Component(...)` and `@Deprecated(...)`, _then_ put it on the previous line? Or maybe the rule could be that the annotation is something other than a single identifier, then it gets its own line, otherwise it goes on the same line?

**Comment by munificent** [comment]
Using capitalization feels pretty magical to me.

I'm up for doing something here, but I'm not sure what. For now, let's leave this bug open and see if any ideas or consensus emerge.

**Comment by munificent** [comment]
This has been quiet for a while so I'm going to go ahead and close it under the assumption that users seem to be happy enough with the status quo.
