### ISSUE TITLE
Constructor with parameters with trailing comma and initializer list inserts extra newline

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/dart_style#658]
What I get:

```
class A {
  A(
    int a,
  )
      : super();
}
```

What I expected :

```
class A {
  A(
    int a,
  ) : super();
}
```

**Comment by gspencergoog** [comment]
We often see this when writing Flutter code:

```dart
class Foo {
  Foo({
    Bar bar,
    Baz baz,
  })
      : assert(bar != null),
        super(baz);
}
```

Dartfmt adds a newline and an indent before the initializer list colon when argument lists are one-to-a-line formatted.

**Comment by gspencergoog** [comment]
I'm so glad you fixed this!  Unfortunately, it seems to add an extra space before the colon, making it
the only punctuation where we have two spaces on one side and one on the other...

It now formats it like this:

```dart
class Foo {
  Foo({
    Bar bar,
    Baz baz,
  })  : assert(bar != null),
        super(baz);
}
```

Which has two spaces before the colon, and aligns all of the following lines on the "a" in assert.

I would have expected this: 

```dart
class Foo {
  Foo({
    Bar bar,
    Baz baz,
  }) : assert(bar != null),
       super(baz);
}
```

Which has one space on either side of the colon, and still aligns on the assert.

**Comment by munificent** [comment]
> Unfortunately, it seems to add an extra space before the colon, making it
the only punctuation where we have two spaces on one side and one on the other...

I know. :( I don't think there's a perfect solution to this. If we only do one space, then it means subsequent lines are indented +5, which would be the only place we do that. Worse, it means that changing the last parameter of the parameter list from optional to mandatory or vice versa would change the indentation of all of the subsequent initializer lines.

Given that, I felt it was better to always have the initializers indented the same, and then add an extra space or two before the `:` to line up the first one.

**Comment by gspencergoog** [comment]
Yeah, I can see the dilemma. Indenting +5 is also not ideal for IDEs, since they want to indent by a multiple of the indent size (it's actually hard to delete one space at the beginning of the line).

However, the only data point I have is that every reviewer I've put that in front of has asked me to change it back to one space on either side, and indent by +5, and having to do that for every constructor I write is going to be tedious (especially because it's hard to delete one space at the beginning of a line).

Given that, I would still vote for indenting by +5, and letting dartfmt re-indent when I add/remove something mandatory.

**Comment by gspencergoog** [comment]
I just noticed something else too: dartfmt sometimes puts the extra space there, and sometimes doesn't, depending on the number of initializers.

```dart
  const MyClass({
    this.state,
  }) : super(key: key);
```
doesn't get an extra space, but:

```dart
  const MyClass({
    this.state,
  })  : assert(state != null),
        super(key: key);
```
does get the extra space.

Seems like indenting +5 would be more consistent there too.

**Comment by Hixie** [comment]
> Worse, it means that changing the last parameter of the parameter list from optional to mandatory or vice versa would change the indentation of all of the subsequent initializer lines.

That'll happen anyway, unless you're going to add three spaces if the arguments aren't named.


> If we only do one space, then it means subsequent lines are indented +5, which would be the only place we do that. 

If you want other places where we should indent by odd numbers, so that this isn't the odd one out, then I would point to https://github.com/dart-lang/dart_style/issues/532 (indent by 7 for `return`), as well as similar requests, e.g. that expressions be properly vertically aligned in `while` loops. Right now you get:

```dart
void main() {
  while (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa &&
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb &&
      cccccccccccccccccccccccccccc) {
    // ...
  }
}
```

...which is rather hard to read (especially if those are complex but similar expressions), relative to the more desirable (but indented to an odd number of spaces):

```dart
void main() {
  while (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa &&
         bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb &&
         cccccccccccccccccccccccccccc) {
    // ...
  }
}
```

**Comment by munificent** [comment]
> That'll happen anyway, unless you're going to add three spaces if the arguments aren't named.

Yes, that's what it does now: https://github.com/dart-lang/dart_style/commit/2fc7724e847357b2032cb4bd7212cf8d62dbbc48#diff-9d63bdf180249ada4655b24d02158a6eR138

This means that the indentation of constructor initializers that start their own line is always completely independent of the shape of the constructor's parameter list. Constructors with no parameters, mandatory parameters, optional parameters, and with and without trailing commas all have initializers that are indented the same. That way, changing the constructor's signature doesn't push the initializers around (except for the first, to keep it lining up with the others).

> If you want other places where we should indent by odd numbers

I'm trying to *not* open that can of worms. :) If we were to open it, we'd have to make sure we have enough appetite to eat them all, and there are many many very slippery worms in there.

**Comment by Hixie** [comment]
Embrace the worms! :-)

FWIW, I don't have a strong opinion on how indented initializers should be. I have much stronger opinions about the other worms, but those are for other bugs.

**Comment by munificent** [comment]
For what it's worth, I've never said I'm opposed to alignment, just that it's complex to implement and I haven't had anywhere near enough time to look into it. (I wouldn't be surprised if it turned out to be a bad idea that caused more user unhappiness than happiness. But I wouldn't be surprised if it worked out either.)

The original bug requesting it is still open: https://github.com/dart-lang/dart_style/issues/508.
