### ISSUE TITLE
CLI: Only print changed files

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#678]
Right now, when running the formatter from the command-line on a large package, it prints a line for each file it looks at, whether or not that file was changed. This produces a lot of noise for very little information, and makes it very hard to see which files actually did change—or worse, whether a file had a syntax error. It would be much easier to understand if it only printed files that were reformatted or failed to parse.

**Comment by munificent** [comment]
Yeah, I'd like to do this too.

**Comment by natebosch** [comment]
Similar to #715

Maybe `-q` for "only changed files" and `-qq` for "completely silent"?

**Comment by cclauss** [comment]
Is this issue fixed?

**Comment by munificent** [comment]
Yes, the new CLI you get using `dart format` (as opposed to `dartfmt`) only prints changed files by default.

**Comment by nex3** [comment]
Is there a way to access that CLI for a specific version of the formatter? In Dart Sass, we run the formatter both from the CLI and from `dart_style`'s Dart API, and we need to make sure we're using the same version of each of these so we get the same formatting.

**Comment by munificent** [comment]
> Is there a way to access that CLI for a specific version of the formatter? 

No, the new CLI isn't directly exposed by dart_style, only through `dart format`. It wouldn't be too much trouble to add another entrypoint to do that, but I was trying to avoid increasing the surface area I need to support so didn't. So that means you always get whatever version of dart_style was bundled with the version of the Dart SDK you run `dart format` from.

> we need to make sure we're using the same version of each of these so we get the same formatting.

I'm guessing you used `pub run` to run it? If you want to run the formatter from a dependency on dart_style, you're probably better off still using the old CLI, which is still supported.
