### ISSUE TITLE
Formatting deletes newline before comments

### ISSUE THREAD

**Issue by NatoBoram** [dart-lang/dart_style#681]
From [797](https://github.com/Dart-Code/Dart-Code/issues/797).

Let's say I have a nicely formatted function : 

```Dart
/// Send a packet and register the callback
void send(String action, Map<String, Object> data) {
  
  // Create callback
  int cback = new DateTime.now().millisecondsSinceEpoch;

  ...
}
```

Now, I'll write code somewhere else in the document, and then it'll need to be formatted. Obviously, I'll run the "Format Document" shortcut, but then the first comment of every functions receives some undesired sexual advances from the formatter.

```Dart
/// Send a packet and register the callback
void send(String action, Map<String, Object> data) {
  // Create callback
  int cback = new DateTime.now().millisecondsSinceEpoch;

  ...
}
```

So, yeah. If the formatter didn't abuse everyone's project's readability, that'd be great.

**Comment by srawlins** [comment]
If we're just taking a subjective vote, I find it just as readable afterwards.

**Comment by NatoBoram** [comment]
@srawlins You might find this *subjectively readable*, but it's not *objectively better*.

**Comment by matanlurey** [comment]
Looks like this is covered by https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code

**Comment by NatoBoram** [comment]
No, it's not. There's an error in this tool and it should be fixed.

> Why can't I tell the formatter to ignore a region of code?

You're in luck, i'm not asking for that. You guys should take example on [gofmt](https://blog.golang.org/go-fmt-your-code).

**Comment by srawlins** [comment]
>> Looks like this is covered by https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code

> No, it's not.

@NatoBoram Then your issue description is misleading or vague. You wrote that you liked how your `send` function was formatted, then wrote other code, not depicted, which needs to be formatted, so you ran the formatter, and it undesirably changed your `send` function. That really sounds like [#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code) to me.

> You guys should take example on [gofmt](https://blog.golang.org/go-fmt-your-code).

@NatoBoram you might have to be more specific. You just linked to a blog post introducing gofmt. Did you mean to link to... a specific attribute or policy of gofmt or something?

Either way, I think I see where you're coming from: the formatter already gives leeway on blank lines between statements (and members?), so it will neither remove nor add any lines to the following:

```dart
fn() {
  var a = 1;
  var b = 2;

  var c = 3;
  // comment.
  var d = 4;

  // comment.
  var e = 5;
}
```

The formatter thinks that the author of this code _wanted_ a blank line before declaring `c`, but _not_ before declaring `b`, maybe to break the single statement block into smaller semantic stanzas, and the formatter respected that. You wish it would also respect a blank line at the top of a statement block.

**Comment by munificent** [comment]
This is working as intended. The formatter removes any blank lines at the start of a block (i.e. after a `{`). In general, the formatter's goal is to control as much of the whitespace as possible so that code is consistently formatted and so that users don't have to worry about manually controlling whitespace.

There are a few places where it preserves a blank line in the original code because that can be important for things like separating a series of statements into meaningful regions. The top of a block isn't one of those places.

> You might find this subjectively readable, but it's not objectively better.

One of the formatter's primary jobs is to make subjective choices so that users no longer need to argue over them.

I'd like to make a suggestion about tact and collaborating with others in open source. Because most open source work is done for free, the only way to get people to make your changes is to *persuade* them to *want* to make those changes. People are more likely to want to make you happy if you approach them and their work with kindness and respect. Referring to the formatter's work as "undesired sexual advances" or "abuse" is unlikely to endear me to you and make me want to change its behavior.
