### ISSUE TITLE
Respect empty line at top of code block

### ISSUE THREAD

**Issue by weenzeel** [dart-lang/dart_style#691]
Assume the following class:

```Dart
class MyAbstraction {
  
  var someProperty = '';
  
  var otherProperty = 0;
  
  void doStuff() {
    someProperty = 'Hello!';
    otherProperty = 10;
  }
  
}
```

After formatting:

```Dart
class MyAbstraction {
  var someProperty = '';

  var otherProperty = 0;

  void doStuff() {
    someProperty = 'Hello!';
    otherProperty = 10;
  }
}
```

I think it would improve readability of code if we were allowed to separate the end of the class definition (which may be complex) with a new line before the definitions of other class members. The behavior of the the formatter feels a bit inconsistent when it allows blank lines between members but not between class definition and member definitions.

This also applies to other definitions, like functions and methods and their encapsulated members.

Thanks for your consideration.

**Comment by weenzeel** [comment]
Thanks for commenting.

I understand this to be by design, because it would be such a visible bug if it weren’t. As a designer, trying to learn to code, this just seems like an odd opinion for the formatter to implement.

I'm a designer, and we learn the “law of proximity” by heart; objects or shapes that are close to one another appear to form groups.

@munificent writes in the thread you referenced:

> There are a few places where it preserves a blank line in the original code because that can be important for things like separating a series of statements into meaningful regions. The top of a block isn't one of those places.

I would argue that the top of a block is a meaningful region. This may be where I learn what parameters a method expects vs the names of variables encapsulated by the block.

Let’s look at more complex method definition:

```Dart
_encodeProperty(ModelDBImpl db, Model model, mirrors.InstanceMirror mirror,
    Map properties, String fieldName, Property prop) {
  String propertyName = prop.propertyName;
  if (propertyName == null) propertyName = fieldName;

  var value =
      mirror.getField(mirrors.MirrorSystem.getSymbol(fieldName)).reflectee;
  if (!prop.validate(db, value)) {
    throw new StateError('Property validation failed for '
        'property $fieldName while trying to serialize entity of kind '
        '${model.runtimeType}. ');
  }
  properties[propertyName] = prop.encodeValue(db, value);
}
```

As the human eye scans this code, it will note three distinct regions of code by the law of proximity. To deduce that the top group actually contains two different types of information, I must refocus and spend mental energy reading through the perceived paragraph, locating the signs that separate the public interface from the private implementation. I would be happier if the information was white spaced in a way that helps me process the information in the cheap parts of my brain, instead of the expensive parts.

No big deal, I just know that for this the dart formatter would get critique from my art director if it delivered this typography at the end of our next design sprint ;)

**Comment by munificent** [comment]
> I'm a designer, and we learn the “law of proximity” by heart; objects or shapes that are close to one another appear to form groups.

I'm a designer too, and proximity is definitely something I think about when it comes to formatting.

My personal style in other languages, especially C, is to put the `{` on its own line in large part to separate out the function signature from the body like you describe. However, for Dart, we went with trailing `{` because that was the style users overwhelmingly were using in practice.

Likewise, almost all hand-formatted functions do not have a blank line at the top of the body. Therefore, it would be really jarring if dartfmt inserted them into every function. It could preserve a blank line if present, but that takes a step away from the formatter's primary goal which is consistency.

Instead, it always removes that blank line. That leaves code that is consistently formatted for all users and that agrees with how most users prefer their code. In practice, doing so doesn't seem to harm readability in any noticeable way.

**Comment by weenzeel** [comment]
>  doing so doesn't seem to harm readability in any noticeable way.

Agree to disagree ;)

But thanks for taking the time to comment, and for providing this tool for free.
