### ISSUE TITLE
(Set Literals) Dartfmt Support

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/dart_style#751]
***** Request: 
As per implementation Plan:

Task9 : Task3 (Dartfmt support)
Dartfmt implements formatting support.

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by munificent** [comment]
Before I can support this in dartfmt, the analyzer API will need to be updated to parse and expose the ASTs for the new syntax. Is https://github.com/dart-lang/sdk/issues/35120 the right bug to track for that?

**Comment by bwilkerson** [comment]
I believe that the support you need is now published in version 0.33.5 of the analyzer package. I'm fairly sure that the AST changes made into that version; I'm less certain about the parsing and related changes. Let us know if this version turns out to not be sufficient.

Note that even if all of the support you need is available in that version, it's all behind the `set-literal` flag.

**Comment by bwilkerson** [comment]
Ok, now that I say that I don't see how that could be. The AST changes are a breaking change and this didn't update the major version. So something's wrong. Probably my understanding of which changes are included in that version.

**Comment by bwilkerson** [comment]
We have now published a version 0.34.0 of the analyzer package. I believe that should contain the support you need, but if it doesn't, please let us know.
