### ISSUE TITLE
Method chain always collapses into single line

### ISSUE THREAD

**Issue by passsy** [dart-lang/dart_style#756]
`darfmt` doesn't respect newlines for method chains. Making a single line statement out of a multi-line method chain reduces readability.

```dart
// input
void testFormatting(List<String> list) {
  list.map((it) => it.toString())
      .map((it) => it.toString())
      .forEach(print);
}
```

```dart
// dartfmt output
void testFormatting(List<String> list) {
  list.map((it) => it.toString()).map((it) => it.toString()).forEach(print);
}
```

**Comment by munificent** [comment]
This is working as intended. In general, the goal of dartfmt is to look at the incoming whitespace as *little* as possible. Its job is to produce a consistent style, and any time it looks at the hand-authored whitespace is a chance for the output to diverge in different ways based on the human author's formatting.

For method chains, most users seem happy to have them collapsed when they fit, so this is doing what it's supposed to.

**Comment by passsy** [comment]
Removing whitespace is only one of the goals of this project. What about

> Resulting code should follow the Dart style guide but, moreso, **should look nice to most human readers, most of the time.**

Method chains very common in reactive programming. Right now they never look for any human reader.

`dartfmt` doesn't remove empty lines between two statements, to make it easier to read for humans.

```dart
  final a = "a";

  // dartfmt keeps empty line above
  final b = "a";
  final c = "c";
```

The same rule should be applied for manually added newlines in a method chains.

**Comment by munificent** [comment]
> Method chains very common in reactive programming. Right now they never look nice for any human reader.

It has been formatting method chains this way in millions of lines of code for thousands of users for years. I think that's pretty good evidence that it does look nice to most users most of the time.

> dartfmt doesn't remove empty lines between two statements, to make it easier to read for humans.

Yes, I wished it could be more prescriptive there too. One idea I'd have is to always put a blank line before a line comment inside a block. But, in practice, there are too many useful blank lines and not enough idioms in the code that the formatter could use to base heuristics on, so I was unable to automate controlling blank lines between statements.

Note that it *will* remove blank lines if you try to place more than one. It also removes blank lines at the beginning and end of blocks, extra blank lines between classes and members, etc. In other words, it does control the newlines there as much as it feasibly can.

**Comment by Maistho** [comment]
Hi, I would like to put in a feature request to change this behaviour to produce more readable code.

When working with `rxdart` it is very common to chain operators, and the resulting code is much more readable if every operator is at a seperate line.

Considider the following code
```dart
// Before formatting, unreadable
Observable.fromIterable([1,2,3]).skip(1).debounceTime(Duration(seconds: 5)).listen((values) { print(values); });
```
`dartfmt` will format this into a nice readable thing with newlines between each method in the chain:
```dart
// After formatting, readable!
Observable.fromIterable([1, 2, 3])
    .skip(1)
    .debounceTime(Duration(seconds: 5))
    .listen((values) {
  print(values);
});
```
This is expected behaviour, producing readable code.
If I try adding a trailing comma in order to get my list on multiple lines dart instead tries to fit as much as possible to a single line.
```dart
// After formatting, unreadable
Observable.fromIterable([
  1,
  2,
  3,
]).skip(1).debounceTime(Duration(seconds: 5)).listen((values) {
  print(values);
});
```

I propose that in any method chain of length longer than `x` where `x` is some reasonable number (I like 1, but others may like 2) `dartfmt` should split each method call onto a separate line, producing the following code for the last example:
```dart
// After formatting, readable
Observable.fromIterable([
  1,
  2,
  3,
])
    .skip(1)
    .debounceTime(Duration(seconds: 5))
    .listen((values) {
  print(values);
});
```
I do not think that `dartfmt` should respect the newlines given by the developer in this case, but insert newlines where appropriate.

**Comment by munificent** [comment]
> any method chain of length longer than x where x is some reasonable number (I like 1, but others may like 2

The hard part is picking a reasonable `x`. In general, I try to avoid heuristics based on an arbitrary constant number because, well, it's arbitrary. Picking one is unlikely to satisfy a large number of users, and it's hard in practice to pick one that feels right a majority of the time given the wide range of identifier lengths.

**Comment by Maistho** [comment]
@munificent I think most people would be happy enough with 2, but I agree that picking a reasonable `x` is something where people are likely to have differing opinions.

**Comment by dalewking** [comment]
One workaround is adding trailing //s as in:
```
Observable.fromIterable([1, 2, 3]) //
    .skip(1) //
    .debounceTime(Duration(seconds: 5)) //
    .listen((values) {
  print(values);
});
```

**Comment by dalewking** [comment]
So I notice for .. operator it does force the new lines when you have more than one. Take for example this:

    final iocContainer = GetIt.instance..configureApi()..configureUi();

If I save that dartfmt automatically turns that into:

final iocContainer = GetIt.instance
  ..configureApi()
  ..configureUi();

The question is why does that rule apply to the .. operator but not the . operator?

But I think we need to distinguish on the . operator between its use for properties (which I don't think we want each property on its own line) and its use for method invocations where it is generally accepted that each operation should be on its own line (unless there is only one).

**Comment by munificent** [comment]
> The question is why does that rule apply to the .. operator but not the . operator?

Mainly because the cascade can be *fantastically* unreadable if you don't do that. Consider:

```dart
object.a = b..c = d;
```

Any bets as to what object `b` gets called on?

> But I think we need to distinguish on the . operator between its use for properties (which I don't think we want each property on its own line) and its use for method invocations

The formatter does distinguish those in cases where it needs to split. It will keep a series of properties together while splitting methods that follow it if it can.

> it is generally accepted that each operation should be on its own line (unless there is only one).

I don't know if we have evidence that that *is* generally accepted. For what it's worth, dartfmt has worked this way for a very long time and few users have complained. If I search a corpus of public Dart code, I see tens of thousands of method chains that are single line. Many of those are likely *caused* by dartfmt, but if the authors of those didn't like the result, we'd likely have heard about it by now.

I don't think users would be happy with forced splits in code like:

```dart
int r = (color.r * 255).floor().clamp(0, 255);
value.toUtc().toIso8601String();
testClient.stream(1).toList();
var pct = (100 * totalValid / totalExamples).toStringAsFixed(1).padLeft(5);
return findAll().where(test).toList();
await cache.fetch(id).firstWhere((_) => true, orElse: () => null);
```

**Comment by Maistho** [comment]
This is just me, but I prefer having these examples on separate lines.

But all your examples are only 2 methods chained, do you think users also prefer having 3 methods chained on the same line? I think that splitting every method chain longer than 2 would make most code more readable. 

```dart
int r = (color.r * 255)
  .floor()
  .clamp(0, 255);

value
  .toUtc()
  .toIso8601String();

testClient
  .stream(1)
  .toList();

var pct = (100 * totalValid / totalExamples)
  .toStringAsFixed(1)
  .padLeft(5);

return findAll()
  .where(test)
  .toList();

await cache
  .fetch(id)
  .firstWhere((_) => true, orElse: () => null);
```

**Comment by dalewking** [comment]
> > The question is why does that rule apply to the .. operator but not the . operator?
> 
> Mainly because the cascade can be _fantastically_ unreadable if you don't do that. Consider:
> 
> ```dart
> object.a = b..c = d;
> ```
> 
> Any bets as to what object `b` gets called on?

Not sure your question even makes sense. And that is talking about properties not method calls and the suggestion here is specifically about chained method calls.

> > it is generally accepted that each operation should be on its own line (unless there is only one).
> 
> I don't know if we have evidence that that _is_ generally accepted. For what it's worth, dartfmt has worked this way for a very long time and few users have complained.

It definitely is generally accepted in the general programming world. What we are talking about is [method chaining](https://en.wikipedia.org/wiki/Method_chaining) or a [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface). Notice the examples under fluent interface where each method call is on its own line.

Try doing a google search on "fluent interface formatting" and you will find countless examples of this style of formatting including people filing issues that some formatter in another language did not format it "correctly"

Based on the evidence of countless other languages, it is generally accepted that with chained method calls it is more readable to have one method call per line with the . starting the line.

> If I search a corpus of public Dart code, I see tens of thousands of method chains that are single line. Many of those are likely _caused_ by dartfmt, but if the authors of those didn't like the result, we'd likely have heard about it by now.

You heard about ia a year ago (this issue) and are hearing about it now. Until a year ago not that many people were using Dart. Also did people who were bugged by this just turn off dartfmt instead of complaining.

Part of that is also that method chaining or fluent interface isn't as prevalent in dart code. This is partially because Dart has some constructs that are usually used for some of the cases where method chaining is done in other languages. For example, the cascade operator and optional named parameters help eliminate the need to use the [fluent builder pattern](https://dzone.com/articles/fluent-builder-pattern).

I expect method chaining to become much more prevalent now that Dart has extension methods.

One place you cannot get away from it is in RxDart where long method chains are prevalent. Take a look at the [examples in RxDart](https://github.com/ReactiveX/rxdart/blob/master/README.md#for-example-reading-the-konami-code) and you will see the one method per line format.

> I don't think users would be happy with forced splits in code like:
> 
> ```dart
> int r = (color.r * 255).floor().clamp(0, 255);
> 
> value.toUtc().toIso8601String();
> 
> testClient.stream(1).toList();
> 
> var pct = (100 * totalValid / totalExamples).toStringAsFixed(1).padLeft(5);
> 
> return findAll().where(test).toList();
> 
> await cache.fetch(id).firstWhere((_) => true, orElse: () => null);
> ```

Don't know what universe you live in but I find these much more readable when you follow the rule of each method in a chain goes on a separate line. As @Maistho points out the difference is not as dramatic on chain lengths of 2 which is why it was suggested that perhaps it isn't done for chains of length 2.

```dart
int r = (color.r * 255).floor()
    .clamp(0, 255);

value.toUtc()
    .toIso8601String();
 
testClient.stream(1)
    .toList();
 
var pct = (100 * totalValid / totalExamples).toStringAsFixed(1)
    .padLeft(5);
 
return findAll().where(test)
    .toList();

await cache.fetch(id).firstWhere((_) => true, orElse: () => null);
```

**Comment by munificent** [comment]
> But all your examples are only 2 methods chained, do you think users also prefer having 3 methods chained on the same line?

Looking at a corpus of Dart packages, I do see a many examples of method chains more than 2 long on a single line. Some random examples:

```dart
abideYaml.keys.map<String>((k) => k.toString()).toList()..sort();

String colStr = col.toString().replaceAll('[', '').replaceAll(']', '');

await file.openRead().transform(utf8.decoder).transform(LineSplitter());

Input.getValue(widget.id).split("|").toList();

errors.add(matcher.describe(description).toString().trim());

strBuffer.write(strItr.toString().substring(0, 1).toUpperCase());

result.addAll(targetProvince.child.toList().map((p) => p.name).toList());

final words = pattern.allMatches(subject).map((m) => m.group(0)).toList();

var arr = bytes.skip(offset).take(uuidByteLength).toList();

var parser = match('he').forward(2).castDynamic();

ref = storage.ref().child('avatars').child('large').child('image.jpg');
```


> ```dart
> ```dart
> object.a = b..c = d;
> ```
> 
> 
> Any bets as to what object b gets called on?
> 
> Not sure your question even makes sense. 

Oops, sorry, I meant `c`.

> And that is talking about properties not method calls and the suggestion here is specifically about chained method calls.

Yes, but those can (and are) mixed:

```dart
object.a = b..c()..d = e;
```

Cascades support mixing methods, getters, *and setters*, and the latter are so confusing to read when on one line that the formatting rule splits all cascaded calls to multiple lines (except that multiple cascaded method calls to the same method are allowed to pack onto one line).

I got to this set of rules by talking to a number of users and examining a lot of existing hand-formatted code to see what the prevailing style was. This rule seemed to fit pretty well. In particular, the original language designers of cascade syntax explicitly said "it's hard to read if you don't put them on their own lines".

For method chains, you only have methods and getters to worry about and less confusion with precedence caused by cascades and setters. Also, as with cascades, I looked at a lot of hand-formatted code written by many users and saw that packing method chains onto one line was quite common.

> Until a year ago not that many people were using Dart.

We've had thousands of users writing millions of lines of Dart code for several years now.

> Also did people who were bugged by this just turn off dartfmt instead of complaining.

No, inside Google it's mandatory that *all* Dart code is formatted using dartfmt. If any significant fraction of Google Dart developers were bothered by this rule, I would definitely know (because they *have* told me clearly about other rules they were bothered by).

> Don't know what universe you live in

This tone isn't helpful.

For what it's worth, I live in the same universe as the human authors of the code I included. Those people don't seem to share your opinion, or if they do, they don't care enough to say anything.

It is OK if you personally dislike this rule. No set of formatting rules is going to fully please 100% of users. *I* don't like some of the formatting rules. But this rule in particular does not seem to be significantly disliked.

I'm not saying it's perfect or cannot be changed. But with any change that affects a very large number of existing already-formatted lines of code, the risk is always very high that users will be extremely unhappy to see their existing code change under them. This means any change has to be more than just marginally better and must be better in the eyes of a large number of users.

That *may* be the case for this issue, but so far I haven't seen much evidence to support that and I don't have the time right now to invest in trying to seek out that evidence (sending out surveys, doing a trial implementation, etc.) beyond scraping a corpus like I have done for you several times in this issue.

**Comment by Maistho** [comment]
> Looking at a corpus of Dart packages, I do see a many examples of method chains more than 2 long on a single line.

I'm a bit curious, how many of these packages are using dartfmt?

I'm currently using dartfmt because it is the best tool for formatting dart code. I do of course have some issues with some of the formatting, such as the method chaining and that I have to *manually* add trailing commas everywhere when writing Flutter code.

It is still *way* better than handformatting code, so I use it and am generally happy with it. I would guess the same reasoning applies for other users as well. 


> If any significant fraction of Google Dart developers were bothered by this rule, I would definitely know

This actually surprises me, since I would presume that a lot of Dart developers at Google would have backgrounds with JavaScript, like I do. And in JS every auto formatting tool that I've used in the past had either an option to put every method call on a new line, or no option to not do so.


Again some examples of how I would hand format the examples above, for what constitutes far better readability in my opinion.
```dart

abideYaml.keys
  .map<String>((k) => k.toString())
  .toList()
  ..sort();

String colStr = col
  .toString()
  .replaceAll('[', '')
  .replaceAll(']', '');

await file
  .openRead()
  .transform(utf8.decoder)
  .transform(LineSplitter());

Input
  .getValue(widget.id)
  .split("|")
  .toList();

// The ones where an argument to a method call itself has a long chain is even more difficult
// to read in the single line format, although I still find it kind of confusing even when split up.
errors
  .add(
    matcher
      .describe(description)
      .toString()
      .trim(),
  );

strBuffer
  .write(
    strItr
      .toString()
      .substring(0, 1)
      .toUpperCase(),
  );

result
  .addAll(
    targetProvince.child
      .toList()
      .map((p) => p.name)
      .toList(),
  );

final words = pattern
  .allMatches(subject)
  .map((m) => m.group(0))
  .toList();

var arr = bytes
  .skip(offset)
  .take(uuidByteLength)
  .toList();

var parser = match('he')
  .forward(2)
  .castDynamic();

ref = storage
  .ref()
  .child('avatars')
  .child('large')
  .child('image.jpg');
```

**Comment by munificent** [comment]
> I'm a bit curious, how many of these packages are using dartfmt?

I'm not sure. I could try to dig in and find out, but I don't think I have the time right now. Probably most.

> such as the method chaining and that I have to _manually_ add trailing commas everywhere when writing Flutter code.

Yeah, that part is a drag. It's complicated.

**Comment by passsy** [comment]
> I'm a bit curious, how many of these packages are using dartfmt?

[`pana`](https://github.com/dart-lang/pana) gives pub packages a penalty when code exceeds 80 characters. Just my feeling, but I think most packages are using dartfmt to easily get rid of the penalty.

**Comment by munificent** [comment]
> [`pana`](https://github.com/dart-lang/pana) gives pub packages a penalty when code exceeds 80 characters. Just my feeling, but I think most packages are using dartfmt to easily get rid of the penalty.

That's a fairly recent feature added to pub.dev, though. My corpus was a thousand packages, and I think many of them are older than that feature.

**Comment by deakjahn** [comment]
With all due respect, the corpus you refer to is not a valid argument. They look like that because you force that kind of non-splitting on them. So you use the current situtation of your own code to justify the current situation of your own code: :-)

It's you who decide on matters like this in the end, sure, but I can't see **one** single reason not to split when the resulting line exceeds the set line length. There's simply no reference to any existing code that justifies this.

**Comment by passsy** [comment]
> In general, I try to avoid heuristics based on an arbitrary constant number because, well, it's arbitrary. Picking one is unlikely to satisfy a large number of users, and it's hard in practice to pick one that feels right a majority of the time given the wide range of identifier lengths.

[Prettier 2.0](https://prettier.io/blog/2020/03/21/2.0.0.html#improved-method-chain-breaking-heuristic-6685httpsgithubcomprettierprettierpull6685-by-mmkalhttpsgithubcommmkal) introduced heuristics to format method chains. Maybe dartfmt could go in a similar direction.

> Previously, any method call chain of length three or longer would be automatically broken into multiple lines. The new heuristic is based on the complexity of the call arguments in the chain, rather than simply on the chain's length. Now, if chained method calls have arguments which aren't easy to understand at a glance (e.g. functions or deeply-nested objects), the chain is broken. Otherwise, they're allowed to remain on one line.

"easy to understand at a glance" is implemented in [`isSimpleCallArgument`](https://github.com/prettier/prettier/blob/30adb171739c35dc7cb6c4a3e1864d7d7adab454/src/language-js/utils.js#L921-L992).

Maybe just my feeling, but those heuristics could work for a large number of users.

**Comment by munificent** [comment]
> Prettier 2.0 introduced heuristics to format method chains. Maybe dartfmt could go in a similar direction.

Yes, dartfmt also has a *lot* of heuristics around indentation with call arguments and method chains. It is, by far, the most heuristic-y corner of the formatter. The problem with heuristics is that they aren't always right — that's why they're "heuristics" and not "rules". The set of heuristics it uses have been very carefully tweaked over the years and do a good job most of the time, but not all the time. You don't generally notice the things it gets right, but those are the majority of the time. So far, when I tweak the heuristics to fix the problematic cases, it tends to break those good cases enough to outweigh the benefit. I haven't found any rule changes in a while that are a net improvement.

**Comment by dalewking** [comment]
> One workaround is adding trailing //s as in:
> 
> ```
> Observable.fromIterable([1, 2, 3]) //
>     .skip(1) //
>     .debounceTime(Duration(seconds: 5)) //
>     .listen((values) {
>   print(values);
> });
> ```

I wanted to follow on this and apparently there was a change to better support putting chains on separate lines. It still requires using the trailing // but you only need to add one. You do not need to do it on every line just on one of the lines. So here is an example lambda for Isar and formatted by default:
```
          (e) => e.where().sortByOrder().thenByName().watch().map(toWorkspaceEntities),
```

If I edit it to break up into two lines with a trailing `//` as in:
```
          (e) => e//
              .where().sortByOrder().thenByName().watch().map(toWorkspaceEntities),
```
The it will be reformatted to this:
```
          (e) => e //
              .where()
              .sortByOrder()
              .thenByName()
              .watch()
              .map(toWorkspaceEntities),
```
