### ISSUE TITLE
Bad formatting of `native` body function.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#771]
Example:
```dart
class C {
  void
      _SomethingWithAVeryLongName(
          List<int> sixteenLetterers, String fiver, List<int> eightish)
      native 'SomethingWithAVeryLongName'; // ignore: native_function_body_in_non
}
```
The line break between `void` and the name seems unnecessary.

(I know that `native` functions are not valid Dart, but apparently people keep using them anyway. We should give them a better alternative and stop wasting time implementing it in our tools. Until such times ...)

**Comment by munificent** [comment]
That is a little strange looking. :-/

**Comment by munificent** [comment]
It's the ignore comment that's causing problems here because it needs to hang off the same line where it's written, which forces some weird splitting. But I think the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) does a pretty good job:

```dart
class C {
  void _SomethingWithAVeryLongName(
    List<int> sixteenLetterers,
    String fiver,
    List<int> eightish,
  ) native 'SomethingWithAVeryLongName'; // ignore: native_function_body_in_non
}
```
