### ISSUE TITLE
Is it / can it be possible to specify a line is not formatted and override and manually format just one line and let the formatter handle the rest?

### ISSUE THREAD

**Issue by twistedinferno** [dart-lang/dart_style#772]
I use the formatter all the time and it is really very good.  

The following is how I would like the code to be broken up
```
    test("1", () =>
      expect("a really long striiiing", "another really long striiiing"));
```

but the following is how it is formatted
```
    test(
        "1",
        () =>
            expect("a really long striiiing", "another really long striiiing"));
```

Is there a way to tell the code to stay together and not break, override the formatting just for one line?  Maybe by adding a comment??
```
    test("1", () => //
      expect("a really long striiiing", "another really long striiiing"));
```

**Comment by srawlins** [comment]
I've noticed a theme in recent dartfmt complaints that it does not position arrow-functions as you might expect. I've sometimes changed code to instead use a code block, which works well in your case specifically because the closure passed to `test` is not expected to return anything:

```dart
void main() {
  test("1", () {
    expect("a really long striiiing", "aaaanother really long striiiing");
  });
}
```

I think the general theme I've seen is: When an arrow function is placed inside another statement (i.e. as a function argument), including its parameters in parens, **needs to be line-wrapped**, then things might get weird, and one might consider using a function block instead.

**Comment by twistedinferno** [comment]
That is a good idea, the code block saves me a line but I would still prefer to save two!  I was guessing there might be another situation or other whereby I just want to be explicit and say "don't add a line break here"...kind of the reverse of how adding a comment or an extra comma inside a list works.
```
  [1, 2];
  [
    1,
    2,
  ];
  [
    1, //
    2
  ];
```

**Comment by twistedinferno** [comment]
This is more readable
```
    test("1", () =>
      expect("a really long striiiing", "another really long striiiing"));
```

than this
```
    test(
        "1",
        () =>
            expect("a really long striiiing", "another really long striiiing"));
```

**Comment by munificent** [comment]
The question is answered [in the FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code). (It comes up a lot.)

For your specific case here, like @srawlins suggests, this code will look more idiomatic if you use `{}` instead of `=>` for the function.
