### ISSUE TITLE
Bad formatting on lengthy if () statement

### ISSUE THREAD

**Issue by pmock2** [dart-lang/dart_style#775]
Original code:
```
if (page .querySelectorAll('.user-grid-item[data-selected=true]') .length == 1 || 
    page.querySelectorAll('.user-table-item[data-selected=true]').length == 1) {
```

was converted to:

```
if (page
            .querySelectorAll('.user-grid-item[data-selected=true]')
            .length ==
        1 ||
    page
            .querySelectorAll('.user-table-item[data-selected=true]')
            .length ==
        1) {
```

I'm not sure if this formatting is intentional or not. It certainly is not ideal, and should be changed. An ideal case for me might look something like:
```
if (page
       .querySelectorAll('.user-grid-item[data-selected=true]')
       .length == 1 ||
    page
       .querySelectorAll('.user-table-item[data-selected=true]')
       .length == 1) {
```
Notice the proper indentation and the removal of the unnecessary extra space between the `1` and the `==` 

It is also worth mentioning that the above code is not on the first column over the file. Nesting the above `if` statement within another `if` will reproduce this behavior.

**Comment by srawlins** [comment]
Looks like a repeat of https://github.com/dart-lang/dart_style/issues/728.

Another case of "breaking a line to accommodate two 1- or 2-letter tokens makes it hard to read."

**Comment by munificent** [comment]
As noted in #728, this behavior is deliberate, though doesn't look great for some code. The high level goes is to use indentation to reinforce the infix operator precedence. That's important to do because users don't always memorize the precedence table. A goal of the formatter is to have the whitespace help correctly teach the nesting structure of the code.

But if you have really long operands to infix operators, especially left operands, you can get weird looking results. The formatter doesn't promise to *always* produce beautiful output, it just does the best you can with what you give it. Often the best way to get nice looking code is to see the formatting results and slightly tweak things as needed. In this case, I would hoist `page .querySelectorAll('.user-grid-item[data-selected=true]')` and `page.querySelectorAll('.user-table-item[data-selected=true]')` out into local variables.

I don't think there's a way I can tweak the formatter to get the output you want here without producing clearly worse output in a lot of other related cases.
