### ISSUE TITLE
extra space needed before `:` with single initializer

### ISSUE THREAD

**Issue by a14n** [dart-lang/dart_style#792]
Actual:

```dart
class PestoStyle extends TextStyle {
  const PestoStyle({
    double fontSize = 12.0,
  }) : super(
          inherit: false,
        );
}
```

expected:

```dart
class PestoStyle extends TextStyle {
  const PestoStyle({
    double fontSize = 12.0,
  })  : super(
          inherit: false,
        );
}
```

Same issue when the single initializer splits:

Actual:

```dart
  class A {
    A(
      a,
    ) : parameter =
              "some very very long param";
  }
```

Expected:

```dart
  class A {
    A(
      a,
    )   : parameter =
              "some very very long param";
  }
```

**Comment by munificent** [comment]
I'm not sure if we want to do this one, unfortunately.

In general, dartfmt only does indentation at the beginning of lines and doesn't otherwise try to align intra-line content. (See #508 for a bit more discussion.) I worry that if we take this change then users will file bugs asking why there's an extra space before the `:`.

**Comment by munificent** [comment]
(Oops, didn't mean to click "Close".)

**Comment by a14n** [comment]
>doesn't otherwise try to align intra-line content.

It already adds spaces for initializer list with several entries:

```dart
class A {
  final a;
  const A(
    p,
  )   : a = p,
        super();
}
```

This absence of space makes the split indentation the only place with an inconsistant indentation.

```dart
class A {
  final a;
  const A.c1(
    p,
  ) : super(
          a: p,
        );
//    ^^   WAT

  // with several elements in initializer list, no problem
  const A.c2(
    p,
  )   : a = p,
        super(
          a: p,
        );
}
```

**Comment by munificent** [comment]
> It already adds spaces for initializer list with several entries

Yeah, I agonized over that one. :-/

**Comment by munificent** [comment]
I don't think there's an ideal way to format constructor initializer lists. They're just pretty syntactically weird. If we don't do extra padding before the `:` then it means a change to the parameter list (adding or removing optional parameters) might force the entire initializer list to be indented differently, which increases churn. But if we do add that padding, it looks weird and unnecessary.

I spent a *lot* of time inspecting how hand-formatted initializer lists in the Flutter repo are styled. It turns out they are pretty inconsistent, but I aimed to follow the most common styles I could see there. That was to not do padding and accept that the initializer list might get shifted if you change whether or not the constructor has optional parameters.

The style isn't perfect, but I think it's about as good as I can get it. With the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253), you get:

```dart
class PestoStyle extends TextStyle {
  const PestoStyle({
    double fontSize = 12.0, // comment to force split
  }) : super(
         inherit: false, // comment to force split
       );
}
```

And:

```dart
class A {
  A(
    a, // comment to force split
  ) : parameter =
          "some very very very very very very very very very long param";
}
```

And:

```dart
class A {
  final a;
  const A.c1(
    p, // comment to force split
  ) : super(
        a: p, // comment to force split
      );
}
```
