### ISSUE TITLE
Nested single-element lists have (too) many newlines

### ISSUE THREAD

**Issue by whesse** [dart-lang/dart_style#797]
I wrote some code, and it was formatted like this:

```
  // Group the summaries by blamelist end, blamelist begin, and config set.
  List groups = [
    [
      [
        [data.first]
      ]
    ]
  ];
  SummaryData previous = data.first;
  for (SummaryData summary in data.skip(1)) {
    if (previous.commits.max != summary.commits.max) {
      groups.add([
        [
          [summary]
        ]
      ]);
    } else if (previous.previousCommits.min != summary.previousCommits.min) {
      groups.last.add([
        [summary]
      ]);
    } else if (previous.configSetKey != summary.configSetKey) {
      groups.last.last.add([summary]);
    } else {
      groups.last.last.last.add(summary);
    }
    previous = summary;
  }

```

Is there some way we can avoid the newlines with single-element lists nested in single-element lists?

**Comment by munificent** [comment]
This is a deliberate formatting choice. We don't want the user to have to worry about newlines in their original code when dealing with nested collection literals. But we also don't want to pack them *too* tightly just because they happen to fit on one line. Something like this isn't easy on the eyes:

```dart
var wat = [[[a, b], [c, [d]], e], f, [g, h]], i, j];
```

So the rule dartfmt has is that only an innermost collection literal is allowed to stay unsplit. Once you nest, the outer ones always split. This is a simple rule and seems to work pretty well most of the time. For what it's worth, I think your example here looks fine.
