### ISSUE TITLE
Dartfmt creates extra lines for operators in if statements with one-line comments

### ISSUE THREAD

**Issue by michaelspiss** [dart-lang/dart_style#815]
In the current version (dartfmt 1.2.7), dartfmt creates extra lines for the operators used in if statements
original:
```dart
bool _test(int char) {
  if(char == 1 // a
      || char == 5 // b
      || char == 19 // c
  ) {
    return true;
  }
  return false;
}
```

after formatting:
```dart
bool _test(int char) {
  if (char == 1 // a
          ||
          char == 5 // b
          ||
          char == 19 // c
      ) {
    return true;
  }
  return false;
}
```

This might be connected with #278 and probably #775 (and thus #728)

**Comment by munificent** [comment]
This is because dartfmt splits after the `||` not before as in your original code. So it sees that the operands do not fit in a single line (because of the line comments) so marks those operators as splitting. And then when they split, it places the newline after the `||`. Hence you get redundant newlines. The fix is to move those `||` to before the line comment, which is idiomatic for how dartfmt splits those operators.

That gives you:

```dart
bool _test(int char) {
  if (char == 1 || // a
          char == 5 || // b
          char == 19 // c
      ) {
    return true;
  }
  return false;
}
```

(It might be nice if dartfmt would move the `||` to before the line comments itself, but dartfmt currently doesn't do any code *reordering*, it just changes whitespace.

**Comment by michaelspiss** [comment]
Thanks for the workaround, I think it makes it a bit unnatural to read and would prefer operators before the lines they concern, but this will at least fix the formatter issues.

**Comment by munificent** [comment]
> I would prefer operators before the lines they concern

Everyone has their own preference, but the primary goal of the formatter is *consistency*. When a Dart user is reading some code, they should be able to focus on the code itself and not get distracted by the formatting preference of its original author.

(And, for what it's worth, I agree with your preference too. But when I designed dartfmt's style, most code in the wild put the `||` at the end of the previous line, so that was the consensus style that I adopted.)
