### ISSUE TITLE
dartfmt wrapping

### ISSUE THREAD

**Issue by ferhatb** [dart-lang/dart_style#865]
Example of formatting:
```
final bool _supportsDecode = js_util.getProperty(
        js_util.getProperty(
            js_util.getProperty(html.window, 'Image'), 'prototype'),
        'decode') !=
    null;
```

Is it possible not to wrap last ```null;``` ?

**Comment by munificent** [comment]
This is working as intended, though I agree it doesn't look great in this case. See [here](https://github.com/dart-lang/dart_style/issues/728#issuecomment-420095250) for some discussion of similar examples. It would be hard to fix examples like this without making other cases look even more confusing, or without adding a lot of complexity to the formatting rules. That complexity has its own cost because then users end up unpleasantly surprised by formatting or by how the formatting changes when they change their code.
