### ISSUE TITLE
Dartfmt should not unfold code

### ISSUE THREAD

**Issue by deadsoul44** [dart-lang/dart_style#876]
I like to use dartfmt a lot with the shortcut. But it unfolds the folded code. Is this intended? To me it is annoying. I think it should not affect folding.

**Comment by natebosch** [comment]
Code folding is a presentation concept in your editor, there isn't anything that `dartfmt` can do that would impact this. I think you'll want to file an issue for the editor you are using.

If you are using intellij I think you can report it here: https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart&_ga=2.151989049.1800530242.1575314385-1678724719.1575314385

If you are using vscode I think you can report it here: https://github.com/Dart-Code/Dart-Code


Closing since this issue isn't actionable in this repo.
