### ISSUE TITLE
formatter should be configurable with a config file ?

### ISSUE THREAD

**Issue by a-eid** [dart-lang/dart_style#883]
dart formatter should:: 

- support a config file. 
- support ignore commands ( per file, per line, possibly per block).

**Comment by awulkan** [comment]
This also needs to be a project-based configuration.
I've increased the 80 character limit locally, but everyone else contributing to my projects will be formatting the code by the 80 character limit, causing lots of git changes.

**Comment by fend25** [comment]
Yes! It's necessary.

**Comment by ciokan** [comment]
I work alone on most of my flutter projects and 2 spaces drives me nuts. I usually use a tab of 6 or 4 (depending on certain nestings) chars so I can follow the code better. Being unable to config even the simplest of things is a bad idea IMHO. Changing the indent in my editors is THE first thing I do after installing it.

**Comment by munificent** [comment]
Hi, please see the FAQ here: https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it.

**Comment by awulkan** [comment]
Don't get me wrong, I'm all for having a unifying code formatting tool. I loved the one in Go. I also understand that it's impossible to create a tool that fits everyone's personal style.

The problem is that the max character count is already configurable, but only on a per-user basis. This leads to users having to manually change their settings as they jump between projects, otherwise it causes huge git diffs due to auto formatting.

This directly goes against the FAQ you linked to where it says:
> "[...] it's easier to read and contribute to each other's code, etc."

The solution to this would be to be able to set a per-project size, that overrides the default size and user's size. It's already configurable, so I don't see a reason to make the configuration actually usable for project maintainers/contributors.

**Comment by munificent** [comment]
> The problem is that the max character count is already configurable, but only on a per-user basis.

This is a fair observation. Honestly, the main reason you can configure line length at all in dartfmt is because that was already supported when I first took over the project and we decided to move towards a single opinionated comprehensive formatting style.

It is sometimes useful to be able to configure this, but it's not something I feel comfortable doubling down on. If I add support for some kind of configuration file for this, the very next day I will get hundreds of feature requests to allow configuring feature *X* in that file, for all possible *X*. And a thousand arguments inside Google will be spawned on each team for whether they should check in a file and, if so, what number to put there.

> Sure, you can break up code into smaller sections, but that's not always possible.

It should always be possible. My experience is that if 80 columns is too short, even inside Flutter build methods, the code is already too big and monolithic to be read easily. Flutter code naturally tends to nest deeper than other code, but 80 columns still gives you like 30-something usable levels of nesting. If you need more than *that*, it probably is best to hoist sections of that out to separate methods or widgets.

Also, I really hope we can come up with other solutions at either the language or library level to mitigate the often gratuitous amount nesting even simple Flutter code requires sometimes.

**Comment by awulkan** [comment]
> Flutter code naturally tends to nest deeper than other code, but 80 columns still gives you like 30-something usable levels of nesting. If you need more than that, it probably is best to hoist sections of that out to separate methods or widgets.

That sounds like a lot of nesting in theory, but in reality is only about 5 widgets and some conditional logic. And in many cases that's not enough due to how verbose Flutter widget trees are.

> Also, I really hope we can come up with other solutions at either the language or library level to mitigate the often gratuitous amount nesting even simple Flutter code requires sometimes.

Now that's something I agree with, but I don't think it will happen anytime soon, if ever. And until then I don't personally see any better option than having a higher column limit.

Anyway, I don't think there's any point in continuing this discussion since there's obviously not going to be any change to the formatter regardless of what people think about it.
