### ISSUE TITLE
unnecessary_lambdas with setState

### ISSUE THREAD

**Issue by long1eu** [dart-lang/dart_style#886]
I'm updating a list in Flutter `setState` like this:
```dart
setState(() => _pages.removeLast());
```

The analyser gives me a warning here. Since `removeLast` returns a value and `VoidCallback` returns void, it doesn't seem a good tear-off candidate.

**Comment by munificent** [comment]
This isn't right repo for this issue. dart_style is where dartfmt lives, but the linter [has its own repo](https://github.com/dart-lang/linter). (I know it's a little confusing because the linter implements many of the guidelines for "Effective Dart", which is also what drives dartfmt's rules.)

But fear not, I think I can help any way. In Dart, it's fine to pass a function that returns any type to some place that expects a void-returning function. The return value will just be safely discarded. So I think this linter rule can be applied here and you can change the code to:

```dart
setState(_pages.removeLast);
```
