### ISSUE TITLE
Collection if and Collection for should dartfmt to the next line

### ISSUE THREAD

**Issue by feinstein** [dart-lang/dart_style#891]
If I have the following code:

```dart
children: <Widget>[
  for (int i = 0; i < 10; ++i)
    MyWidget(),
  ],
```

And I call `dartfmt` on that snippet, this is the result:

```dart
children: <Widget>[
  for (int i = 0; i < 10; ++i) MyWidget(),
  ],
```

Which is syntactically correct, but many of us wants `MyWidget` indented on the next line instead.

Maybe a `,` could be added after the `for` so `drtfmt` would know that we want it at the next line? 

I can see cases where people would want this on the same line, as in:

```dart
if (condition) return;
```

But for collections I don't think this is the case.

**Comment by munificent** [comment]
> I can see cases where people would want this on the same line, as in:
> 
> ```dart
> if (condition) return;
> ```
> 
> But for collections I don't think this is the case.

I do think this is the case, even more so for collections than for statements.

With statements, part of the reason to avoid putting the then statement on the same line is because the statement may do interesting control flow like a return and it could be easy to overlook that if on the same line as the condition. (In practice, this doesn't seem to be much of a problem, but it is the canonical argument against single-line ifs.)

But in a collection, the then element can't be a `return` or `break`. Also, users have a greater expectation for brevity at the expression level.

So far, it seems like almost all users are happy with this behavior. Even back when I originally wrote the proposal, many examples used single-line control flow elements and I can't recall anyone saying they preferred them to always split. I'm going to close this for now because I think the current behavior aligns with what most users want, but if we start hearing otherwise, we can always revisit.

**Comment by feinstein** [comment]
Ok, I guess it's just my personal taste then.
