### ISSUE TITLE
Dratfmt adding 2 spaces between end of constructor and :

### ISSUE THREAD

**Issue by feinstein** [dart-lang/dart_style#902]
I am sorry for opening an issue for something as trivial as this, but I can't find any references if this is desired behavior or not. Flutter at least doesn't seems to follow this.

My code is being formatted as:

```dart
  MyClass(
    this.value, {
    Key key,
  })  : assert(value != null),
        super(key: key);
```

As you can see there a 2 spaces between the `})` and the `: assert`.

I can find multiple Flutter classes that don't follow this (but I know Flutter has its own style guide) and can't find any dart style guidelines for this.

**Comment by natebosch** [comment]
The dart style guideline for this whitespace is to accept what `dartfmt` gives you - we don't write out every detail, we treat `dartfmt` as the spec, and it might change over time.

This choice was made so that the `:` is aligned in the same place (4 spaces after the indentation of the `M` in `MyClass`) regardless of whether the characters preceding it are:
- `})  :` (you used a trailing comma and named arguments)
- `)   :` (you used a trailing comma and positional arguments, there will be 3 spaces in this case)
- `   :` (you didn't use a trailing comma and the `:` is on the line following the closing `)`)

**Comment by feinstein** [comment]
Hmm ok, thanks for the insight.
