### ISSUE TITLE
Constant identifier case forces different indentation

### ISSUE THREAD

**Issue by deakjahn** [dart-lang/dart_style#916]
I'm not sure whether this is intentional but it doesn't look right to me:

```
final void Function(Pointer<NativeFunction<Void Function(Uint8)>> output, Pointer<Uint8> pixels, int width, int height, int quality) _compressJpeg = _NativeLib //
        .lookup<NativeFunction<Void Function(Pointer<NativeFunction<Void Function(Uint8)>>, Pointer<Uint8>, Uint16, Uint16, Uint16)>>("name")
    .asFunction();
```

```
final void Function(Pointer<NativeFunction<Void Function(Uint8)>> output, Pointer<Uint8> pixels, int width, int height, int quality) _compressJpeg = _nativeLib //
    .lookup<NativeFunction<Void Function(Pointer<NativeFunction<Void Function(Uint8)>>, Pointer<Uint8>, Uint16, Uint16, Uint16)>>("name")
    .asFunction();
```

If the variable starts in a capital, the next line will be indented more.

**Comment by munificent** [comment]
There are a few small corners where identifier case does affect formatting, yes. When dartfmt sees `Foo.bar()`, it looks at the case of the first identifier to try to determine whether that is a named constructor or static method call versus being an instance or prefix call. The formatting rules for those different slightly because it tries to bind constructor/static method calls more tightly to the class name.
