### ISSUE TITLE
Can not reformat comment correctly in Ideas

### ISSUE THREAD

**Issue by tolcol** [dart-lang/dart_style#917]
In Jetbrains Ideas or Android Studio,can not reformat comment correctly.
default comment at first colum,like this
```dart
int demoFunc() {
//  default format comment at first colunm
  return 0;
}
````
Correct format in VsCode
```dart
int demoFunc() {
  // default format comment  in vscode
  return 0;
}
````

and i can not changes setting in code style to uncheked "Comment at first column" like other Lagunage code style.

**Comment by munificent** [comment]
Yes, if your comment is at the first column, it will not add indentation to it. This is so that if you comment out code and then reformat, the commented out code does not get indented. So this is working as intended, though I realize it sometimes doesn't do what you want.

**Comment by natebosch** [comment]
FWIW My vote would be to change this behavior.

Do we know how many people follow the convention of putting comments at column 0 to comment out code? The shortcut to comment out a line in VS uses the code indent level, not 0. Same with the popular plugins for vim.

We generally expect people to not check in code with commented out sections, should we be optimizing the formatter for the use case of code that's not in a state to be committed?

This seems like the kind of change would not cause much churn, and would probably do what more people expect.

**Comment by munificent** [comment]
> The shortcut to comment out a line in VS uses the code indent level, not 0. Same with the popular plugins for vim.

IntelliJ always comments at column zero.

> We generally expect people to not check in code with commented out sections, should we be optimizing the formatter for the use case of code that's not in a state to be committed?

That's true within Google, but I think it's less true outside.

For what it's worth, this behavior has been in dartfmt since before I started working on it. @pq might know more about how well motivated it is. It hasn't come up frequently as a user *complaint*, so my guess is that it either (a) mostly does the right thing when users run into it, or (b) that they rarely run into it.

Given that IntelliJ always comments at column zero and that many users format on save, my hunch is that this is useful behavior.

**Comment by pq** [comment]
> @pq might know more about how well motivated it is

I think this was an expedience thing.  I actually like the proposed behavior and in most cases I think it's exactly what you want.  I'm guessing that if the old `dartftmt` didn't add the indent it's because I didn't get to it or it was tricky for some reason.  Sorry I can't remember more precisely!
