### ISSUE TITLE
Allow 2 spaces on getters

### ISSUE THREAD

**Issue by normancarcamo** [dart-lang/dart_style#980]
Hello there, is there a way to set 2 spaces instead of 4 when formatting the code?

```dart

@immutable
abstract class LoginAbstractState extends Equatable {}

class LoginState extends LoginAbstractState {
  final bool isEmailValid;
  final bool isPasswordValid;
  final bool isSubmitting;
  final bool isSuccess;
  final bool isFailure;
  final bool isAppleLoginAvailable;

  @override
  List<Object> get props => [
        isEmailValid,
        isPasswordValid,
        isSubmitting,
        isSuccess,
        isFailure,
        isAppleLoginAvailable,
      ];
// skipped by brevity...
```

**Comment by munificent** [comment]
No, there isn't. The general answer why is [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it). In this specific case, the reasoning is:

* It makes sense to format list literals and map literals the same way when they appear after `=>`.
* Formatting a map literal with only +2 indentation can make it confusing to read because it looks a lot a normal function body if you don't happen to notice the `=>`.

**Comment by normancarcamo** [comment]
I really don't buy the idea, but that's how it works in dart's ecosystems.
thanks.
