### ISSUE TITLE
Formatting call chain is a bit off

### ISSUE THREAD

**Issue by long1eu** [dart-lang/dart_style#989]
Hi!

I really love dartfmt in general but there is this issue that bugs my head.

Why does the following piece of code format like this:
```dart
    _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(<String, dynamic>{
      'relocationOffered': relocation,
      'workSituation': workSituation,
      'zipCode': zipCode,
    });
```

and not like this:
```dart
    _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(<String, dynamic>{
          'relocationOffered': relocation,
          'workSituation': workSituation,
          'zipCode': zipCode,
        });
```

Sure it looks even worse if I do this:
```dart
    _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(<String, dynamic>{
      'relocationOffered': relocation,
      'workSituation': workSituation,
      'zipCode': zipCode,
    }).then((value) => null);
```

But looks perfect if I do this:
```dart
    _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(<String, dynamic>{
          'relocationOffered': relocation,
          'workSituation': workSituation,
          'zipCode': zipCode,
        })
        .then((value) => null)
        .then((value) => null);
```

But of course I can live with something like this:
```dart
    final Map<String, dynamic> data = <String, dynamic>{
      'relocationOffered': relocation,
      'workSituation': workSituation,
      'zipCode': zipCode,
    };

    await _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(data);
```

**Comment by DanWatkins** [comment]
@long1eu  This behavior is actually by design if you read their [FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ#why-isnt-this-function-or-collection-indented-enough). However, I have to agree with you that the output is confusing when coming from other formatters such as Prettier for JS/TS or just about any other code formatter I've used. It would be nice to have an option to indent relative to the surrounding expression. At the end of the day, it might just be something we have to adjust to.

Here is another example where this behavior seems odd to me:

```
Widget build(BuildContext context) {
  return Scaffold(
      body: Column(
    children: [
      Column(
          children: transactions.map((t) {
        return Card(child: Text(""));
      }).toList())
    ],
  ));
}
```

I would personally expect the indentation to be this:

```
Widget build(BuildContext context) {
  return Scaffold(
      body: Column(
      children: [
        Column(
          children: transactions.map((t) {
            return Card(child: Text(""));
          }).toList()
        )
      ],
    )
  );
}
```

**Comment by munificent** [comment]
Yeah, the formatter's heuristics around when to do "block-like" formatting for nested function expressions and collection literals currently lean pretty hard towards block style. That's good for some things like tests:

```dart
test('blah', () {
  // Potentially lots of code here.
});
```

But it doesn't look great in some cases, like your example here. This is a difficult part of the formatter to change because it impacts *so* much existing formatted code and it tends to make some cases better and others worse. Users don't like it when any existing formatted code gets uglier. At some point, though, it may be worth revisiting this.

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) does the right thing. It gives you:

```dart
    _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(<String, dynamic>{
          'relocationOffered': relocation,
          'workSituation': workSituation,
          'zipCode': zipCode,
        });
```

And:

```dart
    _firestore //
        .doc('$_usersCollection/$uid/streams/$streamId')
        .update(<String, dynamic>{
          'relocationOffered': relocation,
          'workSituation': workSituation,
          'zipCode': zipCode,
        })
        .then((value) => null);
```
